Repository act-rules/act-rules.github.io, pull requests merged in 2018-09, with the labels that each got.

#213 Export a11y-testcases
  .gitignore
  Gemfile
  Gemfile.lock
  _config.yml
  _data/sc-urls.json
  _plugins/codesnippetframe_and_testcases_generator.rb
  _plugins/frame_embed_generator.rb
  _plugins/testcases_generator.rb
  assets/css/base.scss
  package.json
  pages/rules.html
  wcag-url-generator.js
Labels: Chore

#249 Guiding on labels instead of prefixes for PRs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Chore

#248 Documentation: Create Defintion of "Done"
  pages/design/definition-of-done.md
Labels: Chore, september-agenda

#256 Update SC4-1-1-unique-id
  _rules/SC4-1-1-unique-id.md
Labels: Rule, enhancement, september-agenda

#274 Fix: SC1-1-1-image-has-name
  _rules/SC1-1-1-image-has-name.md
Labels: Rule
