Repository act-rules/act-rules.github.io, pull requests merged in 2018-12, with the labels that each got.

#358 chore: security vulnerability
  Gemfile
Labels: Chore, december-agenda

#359 chore: remove algorithms dir in favour of glossary
  .gitignore
  pages/glossary/section-of-content.md
  pages/glossary/visible.md
Labels: Chore

#306 Image-has-name test cases should match Applicability
  _rules/SC1-1-1-image-has-name.md
Labels: Rule, bug, november-agenda

#361 chore: consume EARL reports and represent implementation data per rule
  .gitignore
  .nojekyll
  .prettierrc
  _layouts/default.html
  _plugins/report_data_generator.rb
  assets/css/base.scss
  assets/js/default.js
  assets/js/jquery.stickyelement.js
  assets/js/page-implementations.js
  assets/js/page-rules.js
  development.md
  package-lock.json
  package.json
  pages/implementations.md
  pages/rules.html
  wcag-url-generator.js
Labels: Chore, december-agenda
