Repository act-rules/act-rules.github.io, pull requests merged in 2019-06, with the labels that each got.

#592 chore: run prettier
  _rules/no-keyboard-trap-standard-navigation-a1b64e.md
  gatsby/get-git-log.js
  gatsby/get-node-data.js
  src/pages/rules.js
  src/templates/rule.js
  src/utils/render-fragments.js
Labels: Chore

#593 chore: add husky and lint-staged
  package-lock.json
  package.json
Labels: Chore

#596 chore: add accessibility requirements to test cases (json)
  gatsby/create-testcases-of-all-rules.js
Labels: Chore

#591 chore: update dependencies
  package-lock.json
  package.json
Labels: Chore

#586 fix: Make "manual" rules consistent with their SC
  _rules/descriptive-heading-b49b2e.md
  _rules/descriptive-label-cc0f0a.md
  _rules/document-title-is-descriptive-c4a8a4.md
Labels: Agenda item

#587 fix: Make "auto" rules consistent with their SC
  _rules/aria-attr-valid-5f99a7.md
  _rules/aria-state-or-property-allowed-5c01ea.md
Labels: Agenda item

#620 Update filename-is-accessible-name-9eb3f6.md
  _rules/filename-is-accessible-name-9eb3f6.md
Labels: Rule, reviewers wanted

#612 Fix link to equivalent-resource definition in two rules
  _rules/iframe-unique-name-4b1c6c.md
  _rules/links-with-identical-names-serve-equivalent-purpose-b20e66.md
Labels: Editorial, Rule, bug

#628 chore: fix layout of input rules in rules page
  src/components/layout/index.scss
  src/utils/render-fragments.js
Labels: Chore, Website code

#632 fix: add nowrap for date cell in changelog tabulation of rule
  src/utils/render-fragments.js
Labels: Chore, Website code
