Repository act-rules/act-rules.github.io, pull requests merged in 2019-07, with the labels that each got.

#607 Map ARIA rules to ARIA instead of WCAG 4.1.2
  _rules/aria-attr-valid-5f99a7.md
  _rules/aria-state-or-property-allowed-5c01ea.md
  _rules/aria-state-or-property-has-valid-value-6a7281.md
Labels: Agenda item

#600 chore: Update license
  pages/license.md
Labels: Chore

#649 chore: fix broken links in rule template page
  pages/design/rule-template.md
Labels: Chore

#648 chore: update github templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Chore

#651 chore: add usage count for each glossary term
  src/utils/render-fragments.js
Labels: Chore

#652 chore: update rule template for "Required for conformance"
  src/utils/render-fragments.js
Labels: Chore

#603 New "Process" page on website
  pages/design/process.md
  pages/design/review.md
Labels: Agenda item, Chore, On hold

#634 fix: test if definition for all referenced glossary terms exist
  .gitignore
  _rules/html-lang-valid-bf051a.md
  _rules/role-has-required-states-and-properties-4e8ab6.md
  _rules/video-alternative-c5a4ea.md
  _rules/video-audio-alternative-1ec09b.md
  _rules/video-audio-described-1ea59c.md
  _rules/video-description-track-f196ce.md
  _rules/video-has-captions-f51b46.md
  _rules/video-media-alternative-ab4d13.md
  _rules/video-only-alternative-c3232f.md
  _rules/video-only-audio-alternative-d7ba54.md
  _rules/video-only-description-track-ac7dc6.md
  _rules/video-only-element-transcript-ee13b5.md
  _rules/video-only-media-alternative-fd26cf.md
  _rules/video-transcript-1a02b0.md
  test/rule-glossary.test.js
Labels: Chore, Glossary term

#667 Various typos
  _rules/iframe-has-name-cae760.md
  _rules/iframe-unique-name-4b1c6c.md
  _rules/image-button-has-name-59796f.md
  pages/glossary/same-resource.md
Labels: Editorial, Rule

#682 fix: update refs of glossary
  pages/glossary/accessible-name.md
  pages/glossary/rendered-text.md
  pages/glossary/text-content.md
Labels: Chore, Glossary term, Website content

#694 Replace useless visible-on-the-page with visible
  _rules/autocomplete-valid-73f2c2.md
  _rules/no-keyboard-trap-non-standard-navigation-ebe86a.md
  _rules/unique-id-3ea0c8.md
  pages/glossary/visible-on-the-page.md
  pages/glossary/visible-text-content.md
Labels: Glossary term, Rule, Update

#702 Editorial changes
  _rules/audio-have-transcript-2eb176.md
  _rules/autocomplete-valid-73f2c2.md
  _rules/button-has-name-97a4e1.md
  _rules/form-field-has-name-e086e5.md
  _rules/html-lang-valid-bf051a.md
  _rules/iframe-has-name-cae760.md
  _rules/iframe-unique-name-4b1c6c.md
  _rules/image-has-name-23a2a8.md
  _rules/label-content-name-mismatch-2ee8b8.md
  _rules/link-has-name-c487ae.md
  _rules/meta-refresh-bc659a.md
  _rules/role-attribute-has-valid-value-674b10.md
  _rules/role-has-required-states-and-properties-4e8ab6.md
  _rules/video-audio-described-1ea59c.md
  _rules/video-has-audio-alternative-eac66b.md
  _rules/video-has-captions-f51b46.md
  _rules/video-only-alternative-c3232f.md
  _rules/video-transcript-1a02b0.md
  _rules/video-with-audio-has-audio-description-1ec09b.md
  _rules/video-with-audio-has-description-or-transcript-c5a4ea.md
  pages/design/process.md
Labels: Chore, Editorial, reviewers wanted

#716 Citing the AAMs
  _rules/aria-attr-valid-5f99a7.md
  _rules/button-has-name-97a4e1.md
  pages/glossary/accessible-name.md
  pages/glossary/included-in-the-accessibility-tree.md
  pages/glossary/semantic-role.md
Labels: Editorial, enhancement, reviewers wanted

#707 Show "used in" for atomic rules
  build/create-rules-usages.js
  package.json
  src/templates/rule.js
  src/utils/render-fragments.js
Labels: Chore, Website code, Website content, enhancement
