Repository act-rules/act-rules.github.io, pull requests merged in 2019-05, with the labels that each got.

#492 chore: add manual reporting download links to rule
  .gitignore
  README.md
  _data/wcag-em-report-tool-mappings/@graph-additional-meta.json
  _data/wcag-em-report-tool-mappings/@graph-context.json
  _data/wcag-em-report-tool-mappings/@graph-evaluator-meta.json
  _rules/aria-hidden-focus-6cfa84.md
  _rules/document-title-is-descriptive.md
  _rules/filename-is-accessible-name-9eb3f6.md
  _rules/image-button-has-name-59796f.md
  _rules/image-has-name-23a2a8.md
  _rules/no-keyboard-trap-standard-navigation-a1b64e.md
  _rules/page-has-title-2779a5.md
  build/get-implementations.js
  build/get-wcag-sc-metadata.js
  gatsby/copy-testcases-assets.js
  gatsby/create-glossary-uages-in-rules.js
  gatsby/create-pages.js
  gatsby/create-testcases-json.js
  gatsby/create-testcases-of-all-rules.js
  gatsby/create-testcases-of-rule-of-em-report-tool.js
  gatsby/get-node-data.js
  gatsby/queries.js
  package.json
  pages/about.md
  pages/glossary/decorative.md
  pages/glossary/semantic-role.md
  src/components/footer/index.js
  src/components/header/index.js
  src/components/layout/index.js
  src/pages/glossary.js
  src/templates/rule.js
Labels: Chore

#225 Rule: iframe-unique-name
  _rules/iframe-unique-name-4b1c6c.md
  test-assets/iframe-unique-name-4b1c6c/advertising-one.html
  test-assets/iframe-unique-name-4b1c6c/advertising-two.html
  test-assets/iframe-unique-name-4b1c6c/page-one-copy.html
  test-assets/iframe-unique-name-4b1c6c/page-one.html
  test-assets/iframe-unique-name-4b1c6c/page-three-same-as-page-one.html
  test-assets/iframe-unique-name-4b1c6c/page-two.html
  test-assets/iframe-unique-name-4b1c6c/page-with-iframe.html
  test-assets/iframe-unique-name-4b1c6c/sub-dir-2/index.html
  test-assets/iframe-unique-name-4b1c6c/sub-dir/page-one.html
Labels: April 30 deadline, Final call, Rule

#495 Template update - ARIA attribute is valid
  _rules/aria-attr-valid-5f99a7.md
Labels: Chore

#496 Template update - aria-hidden with focusable content
  _rules/aria-hidden-focus-6cfa84.md
Labels: Chore

#497 Template update - ARIA state or property allowed
  _rules/aria-state-or-property-allowed-5c01ea.md
Labels: Chore

#498 Template update - ARIA state or property has valid value
  _rules/aria-state-or-property-has-valid-value-6a7281.md
Labels: Chore

#499 Template update - Audio-only as a media alternative for text
  _rules/audio-as-media-alternative-afb423.md
Labels: Chore

#500 Template update - audio elements have a transcript
  _rules/audio-have-transcript-2eb176.md
Labels: Chore

#501 Template update - audio only has a text alternative
  _rules/audio-only-text-alternative-e7aa44.md
Labels: Chore

#502 Template update - Autocomplete valid
  _rules/autocomplete-valid-73f2c2.md
Labels: Chore

#503 Template update - Buttons have an accessible name
  _rules/button-has-name-97a4e1.md
Labels: Chore

#504 Template update - Heading is descriptive
  _rules/descriptive-heading-b49b2e.md
Labels: Chore

#505 Template update - Form field label is descriptive
  _rules/descriptive-label-cc0f0a.md
Labels: Chore

#506 Template update - Document title is descriptive
  _rules/document-title-is-descriptive.md
Labels: Chore

#507 Template update - Filename is valid accessible name
  _rules/filename-is-accessible-name-9eb3f6.md
Labels: Chore

#508 Template update - Form field has accessible name
  _rules/form-field-has-name-e086e5.md
Labels: Chore

#509 Template update - HTML has lang attribute
  _rules/html-has-lang-b5c3f8.md
Labels: Chore

#542 Template update - video element transcript
  _rules/video-transcript-1a02b0.md
Labels: Chore

#541 Template update - Video-only as a media alternative for text
  _rules/video-only-media-alternative-fd26cf.md
Labels: Chore

#518 Template update - Image has accessible name
  _rules/image-has-name-23a2a8.md
Labels: Chore

#519 Template update - label and name from content mismatch
  _rules/label-content-name-mismatch-2ee8b8.md
Labels: Chore

#520 Template update - Valid body lang attribute
  _rules/lang-valid-de46e4.md
Labels: Chore

#521 Template update- Links have an accessible name
  _rules/link-has-name-c487ae.md
Labels: Chore

#522 Template update - Meta-refresh no delay
  _rules/meta-refresh-bc659a.md
Labels: Chore

#524 Template update - No keyboard trap standard navigation
  _rules/no-keyboard-trap-standard-navigation-a1b64e.md
Labels: Chore

#526 Template update - Role attribute has valid value
  _rules/role-attribute-has-valid-value-674b10.md
Labels: Chore

#528 Template update - attributes are not duplicated
  _rules/unique-attrs-e6952f.md
Labels: Chore

#529 Template update - Id attribute is unique
  _rules/unique-id-3ea0c8.md
Labels: Chore

#530 Template update - video with audio has audio descriptions or transcript
  _rules/video-alternative-c5a4ea.md
Labels: Chore

#531 Template update - video element audio described
  _rules/video-audio-described-1ea59c.md
Labels: Chore

#532 Template update - Video element description track
  _rules/video-description-track-f196ce.md
Labels: Chore

#533 Template update - video with audio has audio description
  _rules/video-audio-alternative-1ec09b.md
Labels: Chore

#534 Template update - Video has audio alternative
  _rules/video-has-audio-alternative-eac66b.md
Labels: Chore

#535 Template update - video has captions
  _rules/video-has-captions-f51b46.md
Labels: Chore

#536 Template update - Video as a media alternative for text
  _rules/video-media-alternative-ab4d13.md
Labels: Chore

#537 Template update - video only has an accesible alternative
  _rules/video-only-alternative-c3232f.md
Labels: Chore

#538 Template update - video only has audio alternative
  _rules/video-only-audio-alternative-d7ba54.md
Labels: Chore

#539 Template update - Video only element has description track
  _rules/video-only-description-track-ac7dc6.md
Labels: Chore

#540 Template update - video only element has transcript
  _rules/video-only-element-transcript-ee13b5.md
Labels: Chore

#523 Template update - No keyboard trap non-standard navigation
  _rules/no-keyboard-trap-non-standard-navigation-ebe86a.md
Labels: Chore

#514 Template update - Image button has accessible name
  _rules/image-button-has-name-59796f.md
Labels: Chore

#513 Template update - Iframes with identical accessible names serve equiv…
  _rules/iframe-unique-name-4b1c6c.md
Labels: Chore

#512 Template update - iframe has an accessible name
  _rules/iframe-has-name-cae760.md
Labels: Chore

#511 Template update - HTML lang and xml:lang match
  _rules/html-xml-lang-match-5b7ae0.md
Labels: Chore

#525 Template update - HTML Page has a title
  _rules/page-has-title-2779a5.md
Labels: Chore

#527 Template update - Role has required states and properties
  _rules/role-has-required-states-and-properties-4e8ab6.md
Labels: Chore

#544 chore: fix invalid frontmatter in updated templates
  _rules/html-lang-valid-bf051a.md
  _rules/unique-id-3ea0c8.md
Labels: Chore, bug

#543 Template update: No keyboard Trap
  _rules/no-keyboard-trap-80af7b.md
Labels: Chore, bug

#547 Chore: Adapt site to ACT Rules CR format
  _rules/aria-attr-valid-5f99a7.md
  _rules/aria-state-or-property-allowed-5c01ea.md
  _rules/aria-state-or-property-has-valid-value-6a7281.md
  _rules/audio-as-media-alternative-afb423.md
  _rules/audio-have-transcript-2eb176.md
  _rules/audio-only-text-alternative-e7aa44.md
  _rules/autocomplete-valid-73f2c2.md
  _rules/button-has-name-97a4e1.md
  _rules/descriptive-heading-b49b2e.md
  _rules/descriptive-label-cc0f0a.md
  _rules/document-title-is-descriptive.md
  _rules/filename-is-accessible-name-9eb3f6.md
  _rules/form-field-has-name-e086e5.md
  _rules/html-has-lang-b5c3f8.md
  _rules/html-lang-valid-bf051a.md
  _rules/html-xml-lang-match-5b7ae0.md
  _rules/iframe-has-name-cae760.md
  _rules/iframe-unique-name-4b1c6c.md
  _rules/image-button-has-name-59796f.md
  _rules/image-has-name-23a2a8.md
  _rules/label-content-name-mismatch-2ee8b8.md
  _rules/lang-valid-de46e4.md
  _rules/link-has-name-c487ae.md
  _rules/meta-refresh-bc659a.md
  _rules/no-keyboard-trap-80af7b.md
  _rules/no-keyboard-trap-non-standard-navigation-ebe86a.md
  _rules/no-keyboard-trap-standard-navigation-a1b64e.md
  _rules/page-has-title-2779a5.md
  _rules/role-attribute-has-valid-value-674b10.md
  _rules/role-has-required-states-and-properties-4e8ab6.md
  _rules/unique-id-3ea0c8.md
  _rules/video-alternative-c5a4ea.md
  _rules/video-audio-alternative-1ec09b.md
  _rules/video-audio-described-1ea59c.md
  _rules/video-description-track-f196ce.md
  _rules/video-has-audio-alternative-eac66b.md
  _rules/video-has-captions-f51b46.md
  _rules/video-media-alternative-ab4d13.md
  _rules/video-only-alternative-c3232f.md
  _rules/video-only-audio-alternative-d7ba54.md
  _rules/video-only-description-track-ac7dc6.md
  _rules/video-only-element-transcript-ee13b5.md
  _rules/video-only-media-alternative-fd26cf.md
  _rules/video-transcript-1a02b0.md
  gatsby/create-page-add-md-context.js
  gatsby/create-testcases-of-all-rules.js
  gatsby/create-testcases-of-rule-of-em-report-tool.js
  gatsby/get-node-data.js
  gatsby/on-create-node.js
  gatsby/queries.js
  package-lock.json
  package.json
  src/pages/rules.js
  src/templates/rule.js
  src/utils/render-fragments.js
Labels: Chore

#430 Glossary and rule update: Cleaning up "non-empty"
  _rules/aria-state-or-property-has-valid-value-6a7281.md
  _rules/autocomplete-valid-73f2c2.md
  _rules/button-has-name-97a4e1.md
  _rules/form-field-has-name-e086e5.md
  _rules/html-has-lang-b5c3f8.md
  _rules/html-lang-valid-bf051a.md
  _rules/html-xml-lang-match-5b7ae0.md
  _rules/iframe-has-name-cae760.md
  _rules/image-button-has-name-59796f.md
  _rules/image-has-name-23a2a8.md
  _rules/lang-valid-de46e4.md
  _rules/link-has-name-c487ae.md
  _rules/role-attribute-has-valid-value-674b10.md
  _rules/role-has-required-states-and-properties-4e8ab6.md
  pages/glossary/non-empty.md
  pages/glossary/whitespace.md
Labels: April 30 deadline, Glossary term, March 31 deadline, Merge ready, Rule

#220 New Rule: Links with identical accessible names serve equivalent purpose
  _rules/6cbcbe.md
  pages/algorithms/equivalent-resource.md
  pages/algorithms/matching-characters.md
  pages/algorithms/same-resource.md
  test-assets/6cbcbe/about/contact.html
  test-assets/6cbcbe/admissions/contact.html
  test-assets/6cbcbe/careers/contact.html
  test-assets/6cbcbe/index-copy.html
  test-assets/6cbcbe/index.html
  test-assets/6cbcbe/page1.html
  test-assets/6cbcbe/page2.html
  test-assets/6cbcbe/page3.html
  test-assets/6cbcbe/redirect.html
  test-assets/6cbcbe/redirect1.html
Labels: April 30 deadline, Final call, Rule

#552 chore: Update site for accessibility and usability
  _rules/no-keyboard-trap-80af7b.md
  gatsby-config.js
  gatsby/create-testcases-json.js
  package-lock.json
  package.json
  pages/contribute.md
  pages/design/definition-of-done.md
  pages/implementations/overview.md
  pages/implementations/reporting.md
  pages/structure/accessibility-support.md
  src/components/footer/index.scss
  src/components/layout/index.js
  src/components/layout/index.scss
  src/images/logo.png
  src/pages/glossary.js
  src/pages/rules.js
  src/styles/base.scss
  src/styles/mixins.scss
  src/styles/variables.scss
  src/templates/rule.js
  src/utils/render-fragments.js
Labels: Chore

#551 chore: Validating rules frontmatter on CI
  .circleci/config.yml
  _rules/autocomplete-valid-73f2c2.md
  _rules/button-has-name-97a4e1.md
  _rules/document-title-is-descriptive-c4a8a4.md
  _rules/form-field-has-name-e086e5.md
  _rules/html-has-lang-b5c3f8.md
  _rules/html-lang-valid-bf051a.md
  _rules/iframe-has-name-cae760.md
  _rules/image-has-name-23a2a8.md
  _rules/lang-valid-de46e4.md
  _rules/link-has-name-c487ae.md
  _rules/links-with-identical-names-serve-equivalent-purpose-b20e66.md
  _rules/no-keyboard-trap-80af7b.md
  _rules/role-attribute-has-valid-value-674b10.md
  _rules/video-only-element-transcript-ee13b5.md
  package-lock.json
  package.json
  pages/contribute.md
  pages/glossary/equivalent-resource.md
  pages/glossary/same-resource.md
  pages/glossary/whitespace.md
  src/utils/render-fragments.js
  test/rule-filename.test.js
  test/rule-frontmatter.test.js
  test/rule-headings.test.js
  test/utils/describe-rule.js
  test/utils/get-all-headings-from-markdown-body.js
  test/utils/get-heading-of-depth.js
  test/utils/get-rules-data.js
Labels: Chore

#488 chore: Update templates to CR format
  pages/design/atomic-template-empty.md
  pages/design/composite-template-empty.md
  pages/design/rule-template.md
Labels: Chore
