Repository act-rules/act-rules.github.io, pull requests merged in 2019-01, with the labels that each got.

#366 fix: update aria vs wai-aria usage
  _rules/SC4-1-1+SC4-1-2-aria-state-or-property-allowed.md
  pages/glossary/interactive-element.md
Labels: Rule, enhancement, reviewer wanted

#382 Editorial update for "Accessible name" in Glossary
  pages/glossary/accessible-name.md
Labels: Editorial, Glossary term, bug

#385 chore: update dependencies (security vulnerability)
  Gemfile
  Gemfile.lock
  package.json
Labels: reviewer wanted

#370 Image button has accessible name
  _rules/image-button-has-name.md
Labels: Rule, december-agenda, reviewer wanted

#378 Fix links on "Iframe has accessible name"
  _rules/SC4-1-2-iframe-has-name.md
Labels: Rule, bug, reviewer wanted

#399 fix: add contribute menu link
  _layouts/default.html
Labels: Chore

#392 fix: change contents of review to coming soon
  _config.yml
  pages/design/outdated/review.md
  pages/design/review.md
Labels: Chore

#391 docs: add implementation and test case documentation
  Gemfile.lock
  _layouts/default.html
  pages/implementations/coverage.md
  pages/implementations/overview.md
Labels: Chore, reviewer wanted

#383 fix: focus style for keyboard navigation of menu
  assets/css/base.scss
Labels: Chore, reviewer wanted

#398 chore: fix update rule template
  pages/design/rule-template.md
Labels: Chore, reviewer wanted

#394 fix: deprecate non relevant pages
  _layouts/default.html
  pages/design/style-guide.md
  pages/structure/aggregation.md
  pages/structure/test-modes.md
Labels: Chore, january-agenda, reviewer wanted

#409 Added SC 2.4.9 to "Link has an accessible name"
  _rules/SC2-4-4+2-4-9+4-1-2-link-has-name.md
Labels: Rule, bug

#384 fix: update test case for rule "aria-hidden-focus"
  _rules/SC4-1-2-aria-hidden-focus.md
Labels: Rule, reviewer wanted
