Repository act-rules/act-rules.github.io, pull requests merged in 2019-11, with the labels that each got.

#988 Identical link name: remove test cases that do not satisfy the SC
  _rules/links-identical-name-equivalent-purpose-b20e66.md
Labels: Final Call 1 week

#990 page-has-title, passed example must satisfy the SC
  _rules/html-page-title-2779a5.md
Labels: Final Call 1 week

#981 Use empty accessible name
  _rules/form-control-accessible-name-e086e5.md
  _rules/iframe-accessible-name-cae760.md
  _rules/image-accessible-name-23a2a8.md
  _rules/image-button-accessible-name-59796f.md
  _rules/link-accessible-name-c487ae.md
  pages/glossary/accessible-name.md
Labels: Definition, Final Call 1 week, Rule Update

#994 Examples in glossary
  pages/glossary/accessible-name.md
  pages/glossary/included-in-the-accessibility-tree.md
  pages/glossary/visible.md
Labels: Definition, reviewers wanted

#419 New rule: Explicit role SVG image has accessible name (7d6734)
  __tests__/spelling-ignore.yml
  _rules/explicit-SVG-image-has-name-7d6734.md
Labels: Final call 2 weeks, Rule, WAI-Tools Year 1.5

#986 Remove acc name tests from 2.4.6 Form control label descriptive (cc0f0a)
  _rules/form-control-label-descriptive-cc0f0a.md
Labels: Final Call 1 week, Rule Update

#995 fix: `autoplay` attribute usage in `no-autoplay-audio` rule (aaa1bf / 4c31df / 80f0bf)
  _rules/auto-play-audio-does-not-exceed-3-seconds-aaa1bf.md
  _rules/auto-play-audio-has-control-mechanism-4c31df.md
  _rules/no-auto-play-audio-80f0bf.md
Labels: Rule Update

#985 Fix definition link of Semantic roles in form-control-accessible-name
  _rules/form-control-accessible-name-e086e5.md
Labels: reviewers wanted

#1013 Editorial changes
  pages/glossary/explicit-role.md
Labels: Editorial, reviewers wanted

#1018 Remove useless empty lines from templates frontmatter
  pages/design/atomic-template-empty.md
  pages/design/composite-template-empty.md
  pages/design/rule-template.md
Labels: Editorial, reviewers wanted

#768 Handling shadow trees and iframe for "Links with identical accessible names..." (b20e66)
  __tests__/spelling-ignore.yml
  _rules/links-identical-name-equivalent-purpose-b20e66.md
  pages/glossary/same-resource.md
  pages/glossary/web-page-html.md
Labels: Final call 2 weeks, Rule Update

#1000 Add "non-empty" before xml:lang under Applicability (5b7ae0)
  _rules/html-page-lang-xml-lang-match-5b7ae0.md
Labels: Final Call 1 week, Rule Update

#989 page-title-descriptive: remove inaccessible title example (c4a8a4)
  _rules/html-page-title-descriptive-c4a8a4.md
Labels: Final Call 1 week, Rule Update

#255 Rule: ARIA required context role (ff89c9)
  __tests__/spelling-ignore.yml
  _rules/aria-required-context-role-ff89c9.md
  pages/glossary/owned-by.md
Labels: Final call 2 weeks, Rule, WAI-Tools Year 1.5

#1037 chore: auto generate technique ids to be ignored for spelling tests
  __tests__/spelling-ignore.yml
  __tests__/spelling.js
Labels: reviewers wanted

#1032 Add understanding links to img-button-name
  _rules/image-button-accessible-name-59796f.md
Labels: reviewers wanted

#1039 fix: update type of `mathml` examples
  _rules/aria-state-or-property-valid-value-6a7281.md
  _rules/html-page-lang-b5c3f8.md
  _rules/html-page-lang-xml-lang-match-5b7ae0.md
Labels: reviewers wanted

#1036 Editorial changes to html-page-lang-valid
  _rules/html-page-lang-valid-bf051a.md
Labels: reviewers wanted
