Repository act-rules/act-rules.github.io, pull requests merged in 2020-08, with the labels that each got.

#1379 html-page-title: include "non-empty" in the title
  _rules/html-page-non-empty-title-2779a5.md
Labels: ACT TF request, Final Call 1 week

#1392 "Image filename is accessible name for image" (9eb3f6): Fix examples
  _rules/image-filename-as-accessible-name-9eb3f6.md
Labels: Final Call 1 week, Rule Update

#1395 Add WCAG non-interference as requirement to rules that need it
  _rules/audio-or-video-avoids-automatically-playing-audio-80f0bf.md
  _rules/auto-update-text-efbfc7.md
  _rules/focusable-no-keyboard-trap-80af7b.md
Labels: Final Call 1 week, Rule Update

#1403 Modernise text contrast rule formatting
  _rules/text-contrast-afw4f7.md
Labels: Final Call 1 week

#1372 "ARIA state or property is permitted" (5c01ea): Make examples compliant with ARIA 1.2
  _rules/aria-state-or-property-permitted-5c01ea.md
Labels: Final Call 1 week, Rule Update

#1417 Update visible label in accessible name
  _rules/visible-label-in-accessible-name-2ee8b8.md
Labels: reviewers wanted

#1418 fix issues with previous_author field
  _rules/aria-required-owned-element-bc4a75.md
  _rules/html-page-lang-b5c3f8.md
  _rules/html-page-lang-valid-bf051a.md
Labels: reviewers wanted

#1422 meta-refresh, add accessibility support note
  _rules/meta-refresh-no-delay-bc659a.md
Labels: reviewers wanted

#1406 Put definition examples in separate pages
  pages/examples/accessible-name.md
  pages/examples/included-in-the-accessibility-tree.md
  pages/examples/programmatic-label.md
  pages/examples/visible.md
  pages/glossary/accessible-name.md
  pages/glossary/included-in-the-accessibility-tree.md
  pages/glossary/programmatic-label.md
  pages/glossary/visible.md
Labels: Final Call 1 week

#1411 Rename "form control" to "form field"
  _rules/form-field-non-empty-accessible-name-e086e5.md
Labels: Final Call 1 week

#1414 Add required aria-checked attribute to ARIA required owns passed example 4
  _rules/aria-required-owned-element-bc4a75.md
Labels: ACT TF request, Final Call 1 week

#1424 Order authors alphabetically
  _rules/aria-required-context-role-ff89c9.md
  _rules/aria-state-or-property-valid-value-6a7281.md
  _rules/attr-not-duplicated-e6952f.md
  _rules/audio-as-media-alternative-afb423.md
  _rules/audio-text-alternative-e7aa44.md
  _rules/audio-transcript-2eb176.md
  _rules/button-non-empty-accessible-name-97a4e1.md
  _rules/css-restrict-orientation-b33eff.md
  _rules/device-motion-disabled-c249d5.md
  _rules/device-motion-user-interface-7677a9.md
  _rules/focusable-no-keyboard-trap-80af7b.md
  _rules/focusable-no-keyboard-trap-non-standard-nav-ebe86a.md
  _rules/focusable-no-keyboard-trap-standard-nav-a1b64e.md
  _rules/heading-descriptive-b49b2e.md
  _rules/html-page-non-empty-title-2779a5.md
  _rules/id-value-unique-3ea0c8.md
  _rules/iframe-identical-name-equivalent-purpose-4b1c6c.md
  _rules/link-non-empty-accessible-name-c487ae.md
  _rules/meta-viewport-b4f0c3.md
  _rules/table-header-cells-refer-to-data-cells-d0f69e.md
  _rules/table-headers-attribute-refer-to-data-cells-a25f45.md
  _rules/video-alternative-for-auditory-eac66b.md
  _rules/video-alternative-for-visual-c5a4ea.md
  _rules/video-as-media-alternative-ab4d13.md
  _rules/video-audio-description-1ea59c.md
  _rules/video-captions-f51b46.md
  _rules/video-description-track-f196ce.md
  _rules/video-only-alternative-for-visual-c3232f.md
  _rules/video-only-as-media-alternative-fd26cf.md
  _rules/video-only-description-track-ac7dc6.md
  _rules/video-only-transcript-ee13b5.md
  _rules/video-strict-alternative-for-visual-1ec09b.md
  _rules/video-transcript-1a02b0.md
  pages/design/rule-design.md
Labels: General for all rules, reviewers wanted

#1429 Replace non breaking spaces by spaces
  _rules/aria-state-or-property-permitted-5c01ea.md
  _rules/form-field-non-empty-accessible-name-e086e5.md
  _rules/heading-non-empty-accessible-name-ffd0e9.md
  _rules/links-identical-name-equivalent-purpose-b20e66.md
  _rules/links-with-identical-names-and-context-serve-equivalent-purpose-fd3a94.md
  _rules/role-attribute-valid-value-674b10.md
  _rules/table-header-cells-refer-to-data-cells-d0f69e.md
  pages/glossary/attribute-value.md
  pages/glossary/background-colors-of-text.md
  pages/glossary/hidden-state.md
  pages/glossary/owned-by.md
  pages/glossary/visible.md
Labels: reviewers wanted

#1408 remove techniques from text-contrast acc mapping
  _rules/text-contrast-afw4f7.md
Labels: Final Call 1 week

#1421 Map video-alternative-for-visual to SC 1.2.8
  _rules/video-alternative-for-visual-c5a4ea.md
Labels: Final Call 1 week

#1420 Add placeholder passed example to form-field-acc-name
  _rules/form-field-non-empty-accessible-name-e086e5.md
Labels: Final Call 1 week
