Repository act-rules/act-rules.github.io, pull requests merged in 2020-10, with the labels that each got.

#1459 Cleanup references
  _rules/attr-not-duplicated-e6952f.md
  _rules/descriptive-link-5effbb.md
  _rules/heading-non-empty-accessible-name-ffd0e9.md
  _rules/image-accessible-name-descriptive-qt1vmo.md
  _rules/image-not-in-acc-tree-is-decorative-e88epe.md
  _rules/link-non-empty-accessible-name-c487ae.md
  _rules/links-identical-name-equivalent-purpose-b20e66.md
  _rules/links-with-identical-names-and-context-serve-equivalent-purpose-fd3a94.md
  _rules/scrollable-element-keyboard-accessible-0ssw9k.md
  _rules/visible-label-in-accessible-name-2ee8b8.md
  _rules/zoom-text-no-overflow-clipping-59br37.md
  test-assets/shared/act-logo.png
Labels: Final Call 1 week, Rule Update

#1447 "audio or video avoids automatically playing audio" (80f0bf / aaa1bf / 4c31df): Feedback from TF.
  __tests__/spelling-ignore.yml
  _rules/audio-or-video-avoids-automatically-playing-audio-80f0bf.md
  _rules/auto-play-audio-does-not-exceed-3-seconds-aaa1bf.md
  _rules/auto-play-audio-has-control-mechanism-4c31df.md
  pages/glossary/attribute-value.md
Labels: ACT TF request, Final Call 1 week, Rule Update

#1466 update meta-viewport rule title
  _rules/meta-viewport-b4f0c3.md
Labels: AGWG request, reviewers wanted

#1452 visible-label: fix minor whitespace
  _rules/printable-characters-shortcut-ffbc54.md
  _rules/visible-label-in-accessible-name-2ee8b8.md
  pages/glossary/same-key-events.md
  test-assets/ffbc54/shortcut.js
  test-assets/ffbc54/styles.css
Labels: ACT TF request, Final Call 1 week

#1441 Resolve TF feedback on "Object has accessible name" 8fc3b6
  _rules/object-has-acessible-name-8fc3b6.md
  test-assets/shared/index.html
Labels: ACT TF request, Final Call 1 week, Rule Update

#1474 "Element marked as decorative is not exposed" (46ca7f): Typo in input aspect
  _rules/element-marked-decorative-is-not-exposed-46ca7f.md
Labels: Editorial, Rule Update, reviewers wanted

#1460 Add background info on extended SC mapping
  _rules/descriptive-link-5effbb.md
  _rules/links-with-identical-names-and-context-serve-equivalent-purpose-fd3a94.md
  _rules/meta-refresh-no-delay-bc659a.md
  _rules/meta-viewport-b4f0c3.md
  _rules/scrollable-element-keyboard-accessible-0ssw9k.md
  _rules/text-contrast-afw4f7.md
  _rules/video-alternative-for-visual-c5a4ea.md
Labels: Final Call 1 week

#1467 explicit-svg-img, add <text> example
  _rules/explicit-SVG-image-non-empty-accessible-name-7d6734.md
Labels: Final Call 1 week

#1465 Clear up link-acc-name examples
  _rules/link-non-empty-accessible-name-c487ae.md
Labels: AGWG request, Final Call 1 week

#1481 link is descriptive, remove unnecessary quotes
  _rules/descriptive-link-5effbb.md
Labels: reviewers wanted

#1478 scrollable-keyboard-acc: add accessibility support note
  _rules/scrollable-element-keyboard-accessible-0ssw9k.md
Labels: reviewers wanted

#1475 scrollable-element-keyboard: improve assumption
  _rules/scrollable-element-keyboard-accessible-0ssw9k.md
Labels: reviewers wanted

#1488 Fix minor formatting / spacing issues
  _rules/object-has-acessible-name-8fc3b6.md
  _rules/scrollable-element-keyboard-accessible-0ssw9k.md
  pages/design/test-cases.md
Labels: Editorial, reviewers wanted

#1471 fix object-has-alt example
  _rules/object-has-acessible-name-8fc3b6.md
Labels: Final Call 1 week

#1480 form-control-label-descriptive: rename control to field
  _rules/form-field-label-descriptive-cc0f0a.md
Labels: reviewers wanted

#1469 visible-label-in-acc-name: editorial updates
  _rules/visible-label-in-accessible-name-2ee8b8.md
Labels: reviewers wanted

#1492 Accessible name: Add note on empty aria-labelledby + slight cleanup
  pages/glossary/accessible-name.md
Labels: Definition, reviewers wanted

#1479 aria-required-owned: remove implicit exception
  _rules/aria-required-owned-element-bc4a75.md
Labels: Final Call 1 week

#1483 Link to related rules in background
  _rules/aria-state-or-property-permitted-5c01ea.md
  _rules/aria-state-or-property-valid-value-6a7281.md
  _rules/button-non-empty-accessible-name-97a4e1.md
  _rules/descriptive-link-5effbb.md
  _rules/html-page-lang-b5c3f8.md
  _rules/html-page-lang-matches-default-ucwvc8.md
  _rules/html-page-lang-valid-bf051a.md
  _rules/html-page-non-empty-title-2779a5.md
  _rules/html-page-title-descriptive-c4a8a4.md
  _rules/image-button-non-empty-accessible-name-59796f.md
  _rules/link-non-empty-accessible-name-c487ae.md
Labels: Final Call 1 week
