Repository act-rules/act-rules.github.io, pull requests merged in 2020-06, with the labels that each got.

#1327 chore: update whitespace / indentation
  _rules/image-non-empty-accessible-name-23a2a8.md
  _rules/meta-viewport-b4f0c3.md
  _rules/object-has-acessible-name-8fc3b6.md
  pages/glossary/clipped-by-overflow.md
Labels: reviewers wanted

#1255 Update examples in "Link has accessible name"
  _rules/link-non-empty-accessible-name-c487ae.md
  test-assets/c487ae/planets.jpg
Labels: Final Call 1 week, Rule Update, reviewers wanted

#1328 clarify mixup of "subtag" and "tag" in language rules
  _rules/element-lang-valid-de46e4.md
  _rules/html-page-lang-valid-bf051a.md
  _rules/html-page-lang-xml-lang-match-5b7ae0.md
  pages/glossary/valid-language-tag.md
Labels: reviewers wanted

#1333 "Image filename as accessible name" and "text contrast" (9eb3f6, afw4f7): Correct paths to test assets
  _rules/image-filename-as-accessible-name-9eb3f6.md
  _rules/text-contrast-afw4f7.md
Labels: Final Call 1 week, Rule Update

#1309 Fix presentational conflict resolution
  _rules/autocomplete-valid-value-73f2c2.md
  _rules/form-control-non-empty-accessible-name-e086e5.md
Labels: Final Call 1 week, Rule Update

#1323 Rule update: `aria-*` attribute is defined in WAI-ARIA (5f99a7)
  _rules/aria-attr-defined-5f99a7.md
Labels: Final Call 1 week

#1335 Add labels to input elements
  _rules/aria-attr-defined-5f99a7.md
  _rules/autocomplete-valid-value-73f2c2.md
Labels: Final Call 1 week, Rule Update

#1343 explicit-svg: remove unnecessary note
  _rules/explicit-SVG-image-non-empty-accessible-name-7d6734.md
Labels: reviewers wanted

#1325 Update expectations in "Error message describes invalid form field value"
  _rules/invalid-form-field-value-36b590.md
Labels: Final call 2 weeks, Rule Update

#1296 Orientation of the page is not restricted using CSS transform property (b33eff): Resolve TF feedback
  _rules/css-restrict-orientation-b33eff.md
  test-assets/b33eff/style.css
Labels: Final call 2 weeks

#1322 Rule update: `iframe` element has accessible name (cae760)
  _rules/iframe-non-empty-accessible-name-cae760.md
  test-assets/SC4-1-2-frame-doc.html
Labels: Final Call 1 week

#1351 Improve formulation of definition of "valid language tag"
  __tests__/spelling-ignore.yml
  pages/glossary/valid-language-tag.md
Labels: Definition, Final Call 1 week

#1355 Link non-empty acc name: editorial changes
  _rules/link-non-empty-accessible-name-c487ae.md
Labels: ACT TF request, reviewers wanted

#1341 image-button-acc: remove unnecessary note
  _rules/image-button-non-empty-accessible-name-59796f.md
Labels: ACT TF request, reviewers wanted

#1350 "role attribute has valid value" (674b10): Prepare for TF review
  _rules/role-attribute-valid-value-674b10.md
Labels: ACT TF request, Final Call 1 week, Rule Update

#1340 html-page-title: minimise the number of notes
  _rules/html-page-title-2779a5.md
Labels: reviewers wanted

#1344 html-page-lang-valid: minimise the number of notes
  _rules/html-page-lang-valid-bf051a.md
Labels: ACT TF request, reviewers wanted
