Repository act-rules/act-rules.github.io, pull requests merged in 2020-05, with the labels that each got.

#1283 `id` attribute value is unique (3ea0c8): Turn failed examples into actual accessibility issues
  _rules/id-value-unique-3ea0c8.md
Labels: Final Call 1 week, Rule Update

#1281 Element with `role` attribute has required states and properties (4e8ab6): Update failed examples
  _rules/role-required-states-and-properties-4e8ab6.md
Labels: Final Call 1 week, Rule Update

#1277 "role attribute has valid value" (674b10): make rule inapplicable if there isn't at least one role
  __tests__/spelling-ignore.yml
  _rules/role-attribute-valid-value-674b10.md
Labels: Final Call 1 week, Rule Update

#1294 button-acc-name: Tweak failed example 2 description
  _rules/button-accessible-name-97a4e1.md
Labels: reviewers wanted

#1266 Make rules consistent with WAI-ARIA 1.2
  _rules/aria-state-or-property-permitted-5c01ea.md
  _rules/aria-state-or-property-valid-value-6a7281.md
  _rules/role-required-states-and-properties-4e8ab6.md
Labels: Final Call 1 week

#1265 audio-text-alt: inapplicable example linking to audio
  _rules/audio-text-alternative-e7aa44.md
Labels: Final Call 1 week

#1264 id-value-unique: add empty id inapplicable example
  _rules/id-value-unique-3ea0c8.md
Labels: Final Call 1 week

#1290 Semantic role break circularity
  _rules/audio-text-alternative-e7aa44.md
  _rules/id-value-unique-3ea0c8.md
  pages/glossary/explicit-role.md
  pages/glossary/implicit-role.md
  pages/glossary/semantic-role.md
Labels: Definition, Editorial, reviewers wanted

#1302 image-accname: fix minor ambiguity in applicability
  _rules/image-accessible-name-23a2a8.md
Labels: reviewers wanted

#1242 add github guidelines doc
  README.md
  github-guidelines.md
Labels: Final call 2 weeks

#1278 Changing titles for auto-playing audio rules -- fixes #1258
  _rules/audio-or-video-avoids-automatically-playing-audio-80f0bf.md
  _rules/auto-play-audio-does-not-exceed-3-seconds-aaa1bf.md
Labels: Editorial, Final Call 1 week

#1249 Updating test case descriptions for `audio` or `video` has no audio that plays automatically' rules
  _rules/audio-or-video-avoids-automatically-playing-audio-80f0bf.md
  _rules/auto-play-audio-does-not-exceed-3-seconds-aaa1bf.md
  _rules/auto-play-audio-has-control-mechanism-4c31df.md
Labels: Editorial, Final Call 1 week, Rule Update

#1213 new rule: Image not in the accessibility tree is decorative
  _rules/__tests__/test-assets.js
  _rules/__tests__/testcase-html-hint.js
  _rules/image-not-in-acc-tree-is-decorative-e88epe.md
  test-assets/shared/fireworks.jpg
  test-assets/shared/pdf-icon.png
Labels: Final call 2 weeks

#1284 "Image filename is accessible name for image" (9eb3f6): Process TF feedback –the easy part
  __tests__/spelling-ignore.yml
  _rules/image-filename-as-accessible-name-9eb3f6.md
  test-assets/image-filename-as-accessible-name-9eb3f6/94251e110d24a4c2b6e6ce76e7203374
  test-assets/image-filename-as-accessible-name-9eb3f6/login
  test-assets/image-filename-as-accessible-name-9eb3f6/login.png
  test-assets/image-filename-as-accessible-name-9eb3f6/nyhavn
  test-assets/image-filename-as-accessible-name-9eb3f6/nyhavn.jpeg
  test-assets/image-filename-as-accessible-name-9eb3f6/pain
  test-assets/image-filename-as-accessible-name-9eb3f6/paris
Labels: Final Call 1 week, Rule Update

#1279 New Rule: object has acessible name (8f3b6)
  object-has-acessible-name-8fc3b6.md
  package.json
Labels: Final call 2 weeks, Rule, reviewers wanted

#1235 Update meta-viewport-b4f0c3.md
  __tests__/spelling-ignore.yml
  _rules/meta-viewport-b4f0c3.md
Labels: Final Call 1 week, Rule Update, reviewers wanted

#1171 New rule: Zoomed text node is not clipped with CSS overflow
  __tests__/spelling-ignore.yml
  _rules/zoom-text-no-overflow-clipping-59br37.md
  pages/glossary/clipped-by-overflow.md
  pages/glossary/viewport-size.md
  test-assets/59br37/poem.html
Labels: Final call 2 weeks

#1260 Rule: Scrollable element is keyboard accessible
  __tests__/spelling-ignore.yml
  _rules/scrollable-element-keyboard-accessible-0ssw9k.md
  pages/glossary/scrollable-element.md
  test-assets/shared/eu-logo.svg
Labels: Final call 2 weeks

#1300 image-accessible-name: improve examples
  _rules/image-accessible-name-23a2a8.md
  test-assets/shared/background.png
Labels: Final Call 1 week

#1304 Has non empty accname
  _rules/button-non-empty-accessible-name-97a4e1.md
  _rules/explicit-SVG-image-non-empty-accessible-name-7d6734.md
  _rules/form-control-non-empty-accessible-name-e086e5.md
  _rules/heading-non-empty-accessible-name-ffd0e9.md
  _rules/iframe-non-empty-accessible-name-cae760.md
  _rules/image-button-non-empty-accessible-name-59796f.md
  _rules/image-non-empty-accessible-name-23a2a8.md
  _rules/link-non-empty-accessible-name-c487ae.md
Labels: Editorial, Final Call 1 week, Rule Update

#1303 Update role-required-states-and-properties-4e8ab6.md
  _rules/role-required-states-and-properties-4e8ab6.md
Labels: reviewers wanted

#1313 ARIA state/prop permitted: Remove "attribute" from expectation
  _rules/aria-state-or-property-permitted-5c01ea.md
Labels: reviewers wanted

#1312 auto-play 3 sec: minor formatting update
  _rules/auto-play-audio-does-not-exceed-3-seconds-aaa1bf.md
  _rules/auto-play-audio-has-control-mechanism-4c31df.md
Labels: dependencies, reviewers wanted

#1310 `autocomplete` attribute has valid value (73f2c2): Remove non integer tabindex
  _rules/autocomplete-valid-value-73f2c2.md
Labels: Final Call 1 week, Rule Update

#1285 "Image filename is accessible name for image" (9eb3f6): Process TF feedback –update applicability
  __tests__/spelling-ignore.yml
  _rules/image-filename-as-accessible-name-9eb3f6.md
Labels: Final Call 1 week, Rule Update

#1315 Definition of Programmatically Determinable
  pages/structure/accessibility-support.md
Labels: reviewers wanted
