Repository act-rules/act-rules.github.io, pull requests merged in 2020-03, with the labels that each got.

#1188 Remove duplicate example in "SVG image with explicit role" (7d6734)
  _rules/explicit-SVG-image-has-name-7d6734.md
Labels: Rule Update, reviewers wanted

#1193 Remove outdated class="target" from examples (b49b2e / a1b64e / ebe86a / 80af7b)
  _rules/focusable-no-keyboard-trap-80af7b.md
  _rules/focusable-no-keyboard-trap-non-standard-nav-ebe86a.md
  _rules/focusable-no-keyboard-trap-standard-nav-a1b64e.md
  _rules/heading-descriptive-b49b2e.md
Labels: Editorial, Rule Update, reviewers wanted

#1201 De-duplicate IDs of Accessibility Supports in Glossary
  pages/glossary/accessible-name.md
  pages/glossary/explicit-role.md
  pages/glossary/marked-as-decorative.md
Labels: Definition, Editorial

#1207 Remove outdated data-rule-target (ee13b5 / c3232f / e7aa44)
  _rules/audio-text-alternative-e7aa44.md
  _rules/video-only-alternative-for-visual-c3232f.md
  _rules/video-only-transcript-ee13b5.md
Labels: Editorial, reviewers wanted

#1194 Use `a` instead of `div role="link"` in examples of "Visible label is part of accessible name" (2ee8b8)
  _rules/visible-label-in-accessible-name-2ee8b8.md
Labels: Final Call 1 week, Rule Update

#1179 Improve example descriptions of "ARIA state or property is permitted" (5c01ea)
  _rules/aria-state-or-property-permitted-5c01ea.md
Labels: Final Call 1 week, Rule Update

#1216 Update note on testing if accessible name is descriptive (97a4e1 / 7d6734 / e086e5 / cae760 / 23a2a8 / 59796f / c487ae)
  _rules/button-accessible-name-97a4e1.md
  _rules/explicit-SVG-image-has-name-7d6734.md
  _rules/form-control-accessible-name-e086e5.md
  _rules/iframe-accessible-name-cae760.md
  _rules/image-accessible-name-23a2a8.md
  _rules/image-button-accessible-name-59796f.md
  _rules/link-accessible-name-c487ae.md
Labels: Editorial, Rule Update, reviewers wanted

#1217 Update examples description of "svg element with explicit role has accessible name" (7d6734)
  __tests__/spelling-ignore.yml
  _rules/explicit-SVG-image-has-name-7d6734.md
Labels: Editorial, Rule Update, reviewers wanted

#1180 Remove smileyface passed example from iframe rule
  _rules/iframe-accessible-name-cae760.md
Labels: Final Call 1 week

#1229 Improve formulation of definition
  pages/glossary/programmatically-determined-link-context.md
Labels: Definition, Editorial, reviewers wanted

#1202 fix(e086e5): update failed example
  _rules/form-control-accessible-name-e086e5.md
Labels: Final Call 1 week

#1211 Add G208 technique to visible-label-in-acc-name
  _rules/visible-label-in-accessible-name-2ee8b8.md
Labels: Final Call 1 week

#1226 Add input aspect to definitions
  pages/glossary/accessible-name.md
  pages/glossary/appropriate-field-for-the-form-control.md
  pages/glossary/background-colors-of-text.md
  pages/glossary/correct-autocomplete-field.md
  pages/glossary/disabled-element.md
  pages/glossary/explicit-role.md
  pages/glossary/focusable.md
  pages/glossary/foreground-colors-of-text.md
  pages/glossary/implicit-role.md
  pages/glossary/included-in-the-accessibility-tree.md
  pages/glossary/large-scale-text.md
  pages/glossary/marked-as-decorative.md
  pages/glossary/non-streaming-media-element.md
  pages/glossary/owned-by.md
  pages/glossary/programmatic-label.md
  pages/glossary/programmatically-determined-link-context.md
  pages/glossary/rendered-text.md
  pages/glossary/semantic-role.md
  pages/glossary/standard-keyboard-navigation.md
  pages/glossary/visible-text-content.md
  pages/glossary/visible.md
  pages/glossary/visual-context.md
  pages/glossary/web-page-html.md
Labels: Definition, Editorial, reviewers wanted

#946 Updating rule-design.md
  __tests__/spelling-ignore.yml
  pages/design/rule-design.md
Labels: Editorial, Final Call 1 week, reviewers wanted

#1234 Updating "Image filename is accessible name for image" for W3C publication
  _rules/image-filename-as-accessible-name-9eb3f6.md
Labels: Editorial, reviewers wanted

#1214 fix: applicability and examples to not consider `whitespace` (de46e4)
  _rules/element-lang-valid-de46e4.md
Labels: Final Call 1 week

#1225 Mapping rules to WCAG techniques, batch 3
  _rules/aria-state-or-property-permitted-5c01ea.md
  _rules/no-auto-play-audio-80f0bf.md
  _rules/role-attribute-valid-value-674b10.md
  _rules/role-required-states-and-properties-4e8ab6.md
  _rules/table-header-cells-refer-to-data-cells-d0f69e.md
  _rules/table-headers-attribute-refer-to-data-cells-a25f45.md
  _rules/text-contrast-afw4f7.md
  _rules/video-alternative-for-auditory-eac66b.md
  _rules/video-alternative-for-visual-c5a4ea.md
  _rules/video-audio-description-1ea59c.md
  _rules/video-captions-f51b46.md
  _rules/video-description-track-f196ce.md
  _rules/video-only-alternative-for-visual-c3232f.md
  _rules/video-only-audio-track-d7ba54.md
  _rules/video-only-description-track-ac7dc6.md
  _rules/video-only-transcript-ee13b5.md
  _rules/video-strict-alternative-for-visual-1ec09b.md
  _rules/video-transcript-1a02b0.md
Labels: Final Call 1 week, General for all rules

#1227 Correct role mismatch in examples of "button has accessible name" [97a4e1]
  _rules/button-accessible-name-97a4e1.md
Labels: Final Call 1 week, Rule Update

#1219 Update example descriptions iframe-acc-name rule
  __tests__/spelling-ignore.yml
  _rules/iframe-accessible-name-cae760.md
Labels: Final Call 1 week

#1210 Improve examples of visible-label-in-acc-name rule
  __tests__/spelling-ignore.yml
  _rules/explicit-SVG-image-has-name-7d6734.md
  _rules/visible-label-in-accessible-name-2ee8b8.md
Labels: Final Call 1 week

#1245 image-filename; improve readability of applicability
  _rules/image-filename-as-accessible-name-9eb3f6.md
Labels: reviewers wanted
