Repository act-rules/act-rules.github.io, pull requests merged in 2020-12, with the labels that each got.

#1506 Unifying starting phrase in applicability
  _rules/aria-attr-defined-5f99a7.md
  _rules/aria-hidden-no-focusable-content-6cfa84.md
  _rules/aria-required-context-role-ff89c9.md
  _rules/aria-required-owned-element-bc4a75.md
  _rules/aria-state-or-property-permitted-5c01ea.md
  _rules/aria-state-or-property-valid-value-6a7281.md
  _rules/attr-not-duplicated-e6952f.md
  _rules/audio-as-media-alternative-afb423.md
  _rules/audio-text-alternative-e7aa44.md
  _rules/audio-transcript-2eb176.md
  _rules/auto-update-text-efbfc7.md
  _rules/autocomplete-valid-value-73f2c2.md
  _rules/button-non-empty-accessible-name-97a4e1.md
  _rules/css-restrict-orientation-b33eff.md
  _rules/device-motion-disabled-c249d5.md
  _rules/device-motion-user-interface-7677a9.md
  _rules/element-marked-decorative-is-not-exposed-46ca7f.md
  _rules/explicit-SVG-image-non-empty-accessible-name-7d6734.md
  _rules/focusable-no-keyboard-trap-80af7b.md
  _rules/focusable-no-keyboard-trap-non-standard-nav-ebe86a.md
  _rules/focusable-no-keyboard-trap-standard-nav-a1b64e.md
  _rules/html-page-non-empty-title-2779a5.md
  _rules/id-value-unique-3ea0c8.md
  _rules/iframe-non-empty-accessible-name-cae760.md
  _rules/image-accessible-name-descriptive-qt1vmo.md
  _rules/image-button-non-empty-accessible-name-59796f.md
  _rules/image-filename-as-accessible-name-9eb3f6.md
  _rules/image-non-empty-accessible-name-23a2a8.md
  _rules/image-not-in-acc-tree-is-decorative-e88epe.md
  _rules/invalid-form-field-value-36b590.md
  _rules/link-non-empty-accessible-name-c487ae.md
  _rules/meta-refresh-no-delay-bc659a.md
  _rules/meta-viewport-b4f0c3.md
  _rules/printable-characters-shortcut-ffbc54.md
  _rules/role-attribute-valid-value-674b10.md
  _rules/role-required-states-and-properties-4e8ab6.md
  _rules/scrollable-element-keyboard-accessible-0ssw9k.md
  _rules/table-header-cell-refers-to-data-cells-d0f69e.md
  _rules/text-contrast-afw4f7.md
  _rules/video-alternative-for-auditory-eac66b.md
  _rules/video-alternative-for-visual-c5a4ea.md
  _rules/video-as-media-alternative-ab4d13.md
  _rules/video-audio-description-1ea59c.md
  _rules/video-captions-f51b46.md
  _rules/video-description-track-f196ce.md
  _rules/video-only-alternative-for-visual-c3232f.md
  _rules/video-only-as-media-alternative-fd26cf.md
  _rules/video-only-audio-track-d7ba54.md
  _rules/video-only-description-track-ac7dc6.md
  _rules/video-only-transcript-ee13b5.md
  _rules/video-strict-alternative-for-visual-1ec09b.md
  _rules/video-transcript-1a02b0.md
  _rules/zoom-text-no-overflow-clipping-59br37.md
  pages/design/atomic-template-empty.md
  pages/design/composite-template-empty.md
  pages/design/rule-template.md
Labels: Final Call 1 week

#1493 new rule: Element with presentational children has no focusable content
  _rules/presentational-children-no-focusable-content-307n5z.md
Labels: Final call 2 weeks

#1513 "Zoomed text node is not clipped with CSS overflow" (59br37): Handle non-length line-height
  _rules/zoom-text-no-overflow-clipping-59br37.md
Labels: Final Call 1 week, Rule Update

#1516 Editorial fix for label-in-name passed example 6
  _rules/visible-label-in-accessible-name-2ee8b8.md
Labels: reviewers wanted

#1393 Cleaning up rule c249d5 "Device motion based changes to the content can be disabled"
  _rules/device-motion-disabled-c249d5.md
Labels: reviewers wanted

#1519 Update element-lang-valid inapplicable examples
  _rules/element-lang-valid-de46e4.md
Labels: reviewers wanted

#1514 "Image button has non-empty accessible name" (59796f): Use "attribute value"
  _rules/image-button-non-empty-accessible-name-59796f.md
Labels: Editorial, Final Call 1 week, Rule Update

#1518 "Table header cell has assigned data cells" (d0f69e): accept assigned header
  _rules/table-header-cell-has-assigned-cells-d0f69e.md
Labels: Final Call 1 week, Rule Update
