Repository act-rules/act-rules.github.io, pull requests merged in 2020-09, with the labels that each got.

#1438 chore: Add missing #
  pages/glossary/semantic-role.md
Labels: reviewers wanted

#1431 object-has-acc-name; fix grammer in acc support
  _rules/object-has-acessible-name-8fc3b6.md
Labels: reviewers wanted

#1334 new rule: HTML page language subtag matches default language
  __tests__/spelling-ignore.yml
  _rules/html-page-lang-matches-default-ucwvc8.md
  pages/glossary/default-page-language.md
Labels: Final call 2 weeks

#1356 Add test case design instructions
  pages/design/rule-design.md
  pages/design/test-cases.md
Labels: Final call 2 weeks

#1415 update autocomplete rule to current writing style
  _rules/autocomplete-valid-value-73f2c2.md
Labels: Final Call 1 week

#1419 make visible text content definition objective
  _rules/visible-label-in-accessible-name-2ee8b8.md
  pages/glossary/visible-text-content.md
Labels: Final Call 1 week

#1430 fix inconsistent name in avoid-autoplay atomic rule
  _rules/audio-or-video-avoids-automatically-playing-audio-80f0bf.md
Labels: reviewers wanted

#1442 image-acc-name: fix minor issue in example description
  _rules/image-non-empty-accessible-name-23a2a8.md
Labels: ACT TF request, reviewers wanted

#1423 "ARIA required context role" (ff89c9): Prepare for TF review
  __tests__/spelling-ignore.yml
  _rules/aria-required-context-role-ff89c9.md
  pages/glossary/owned-by.md
Labels: ACT TF request, Final Call 1 week, Rule Update

#1448 Editorial fix for aria-required-owned as per TF feedback
  _rules/aria-required-owned-element-bc4a75.md
Labels: ACT TF request, Editorial, reviewers wanted

#873 New rule: No keyboard shortcuts use only letter, number, sign or punctuation keys
  __tests__/spelling-ignore.yml
  _rules/printable-characters-shortcut-ffbc54.md
  pages/glossary/block-event.md
  pages/glossary/printable-characters.md
  pages/glossary/same-key-events.md
  pages/glossary/set-of-clearly-labeled-instruments.md
  test-assets/ffbc54/shortcut.js
  test-assets/ffbc54/styles.css
Labels: Final call 2 weeks, Rule, reviewers wanted

#1439 "Role attribute has valid value (674b10): process TF feedback
  _rules/role-attribute-valid-value-674b10.md
Labels: ACT TF request, Final Call 1 week, Rule Update

#1425 "Heading is descriptive" (b49b2e): replace "section of content"
  _rules/heading-descriptive-b49b2e.md
  pages/glossary/section-of-content.md
Labels: Final Call 1 week, Rule Update

#1435 text-contrast: make passed example 7 a failed example
  _rules/text-contrast-afw4f7.md
Labels: ACT TF request, Final Call 1 week

#1456 Table rules fix names
  _rules/table-header-cell-refers-to-data-cells-d0f69e.md
  _rules/table-headers-attribute-refer-to-data-cells-a25f45.md
Labels: Rule Update, reviewers wanted

#1404 Prepare for TF review: `video` element visual-only content has accessible alternative (c3232f)
  _rules/video-only-alternative-for-visual-c3232f.md
  _rules/video-only-as-media-alternative-fd26cf.md
  _rules/video-only-audio-track-d7ba54.md
  _rules/video-only-description-track-ac7dc6.md
  _rules/video-only-transcript-ee13b5.md
Labels: Final Call 1 week, Rule Update, reviewers wanted

#1453 scrollable-region: move note to the background
  _rules/scrollable-element-keyboard-accessible-0ssw9k.md
Labels: reviewers wanted

#1450 visible-label-acc-name: Consistent wording in example descriptions
  _rules/visible-label-in-accessible-name-2ee8b8.md
Labels: reviewers wanted

#1451 id-unique: remove unnecessary note
  _rules/id-value-unique-3ea0c8.md
Labels: ACT TF request, reviewers wanted

#1449 image-filename: move note to background
  _rules/image-filename-as-accessible-name-9eb3f6.md
Labels: reviewers wanted

#1461 meta-viewport: add missing assumption
  __tests__/spelling-ignore.yml
  _rules/meta-viewport-b4f0c3.md
Labels: reviewers wanted

#1462 "Heading has non-empty accessible name" (ffd0e9): Add Accessibility support note on valid but empty aria-labelledby
  _rules/heading-non-empty-accessible-name-ffd0e9.md
Labels: Rule Update, reviewers wanted

#1443 Autocomplete clear issues
  _rules/autocomplete-valid-value-73f2c2.md
Labels: Final Call 1 week, Rule Update
