Repository act-rules/act-rules.github.io, pull requests merged in 2020-07, with the labels that each got.

#1342 page-lang-xml-lang: minimise the number of notes
  _rules/html-page-lang-xml-lang-match-5b7ae0.md
Labels: ACT TF request, reviewers wanted

#960 New rule: Auto-updating text content can be paused or stopped
  __tests__/spelling-ignore.yml
  _rules/auto-update-text-efbfc7.md
  pages/glossary/clearly-labeled-location.md
  pages/glossary/instrument.md
  pages/glossary/user-interaction.md
  test-assets/efbfc7/script.js
Labels: Final call 2 weeks, Rule, reviewers wanted

#1352 Use technically correct language for attribute values
  _rules/aria-hidden-no-focusable-content-6cfa84.md
  _rules/aria-required-owned-element-bc4a75.md
  _rules/aria-state-or-property-valid-value-6a7281.md
  _rules/audio-or-video-avoids-automatically-playing-audio-80f0bf.md
  _rules/auto-play-audio-does-not-exceed-3-seconds-aaa1bf.md
  _rules/auto-play-audio-has-control-mechanism-4c31df.md
  _rules/autocomplete-valid-value-73f2c2.md
  _rules/button-non-empty-accessible-name-97a4e1.md
  _rules/element-lang-valid-de46e4.md
  _rules/id-value-unique-3ea0c8.md
  _rules/video-description-track-f196ce.md
  _rules/video-only-description-track-ac7dc6.md
  _rules/zoom-text-no-overflow-clipping-59br37.md
  pages/glossary/attribute-value.md
Labels: Final call 2 weeks, General for all rules, Rule Update

#1360 Remove "font awesome" example from Link as non-empty accessible name (c487ae)
  _rules/link-non-empty-accessible-name-c487ae.md
Labels: Final Call 1 week, Rule Update

#1357 form-controls-acc-name: Modernise the rule
  _rules/form-control-non-empty-accessible-name-e086e5.md
Labels: ACT TF request, Final Call 1 week

#1345 Add condition list instructions to rule design doc
  __tests__/spelling-ignore.yml
  pages/design/rule-design.md
Labels: Final Call 1 week

#1364 "meta viewport does not prevent zoom" (b4f0c3): Added changes from TF review to rule.
  _rules/meta-viewport-b4f0c3.md
Labels: ACT TF request, Final Call 1 week

#1332 New rule: Element marked as decorative is not exposed
  _rules/element-marked-decorative-is-not-exposed-46ca7f.md
  pages/glossary/marked-as-decorative.md
  pages/glossary/semantic-role.md
Labels: Final call 2 weeks, Rule

#880 New rule: Device motion based functionality can be disabled
  __tests__/spelling-ignore.yml
  _rules/device-motion-disabled-c249d5.md
  pages/glossary/changes-in-content.md
  test-assets/7677a9/slider.js
Labels: Final call 2 weeks, Rule, reviewers wanted

#1276 New rule: Device motion based changes to the content can also be created from the user interface
  _rules/device-motion-user-interface-7677a9.md
  pages/glossary/changes-in-content.md
Labels: Final call 2 weeks, Rule

#1365 Update aria-required-owned-element-bc4a75.md before publishing
  _rules/aria-required-owned-element-bc4a75.md
Labels: reviewers wanted

#1371 "`aria-*` attribute is defined in WAI-ARIA" (5f99a7): put context on failed example 1
  _rules/aria-attr-defined-5f99a7.md
Labels: Final Call 1 week, Rule Update

#1354 New rule: image accessible name descriptive
  _rules/image-accessible-name-descriptive-qt1vmo.md
Labels: Final call 2 weeks

#1363 Prepare "All table header cells have assigned data cells" (d0f69e) for TF review
  _rules/table-header-cells-refer-to-data-cells-d0f69e.md
Labels: ACT TF request, Final Call 1 week, Rule Update

#1387 Update appropriate field for the form control
  pages/glossary/appropriate-field-for-the-form-control.md
Labels: Editorial, reviewers wanted

#1399 Prepare for TF "Object element has non-empty accessible name" (8fc3b6)
  _rules/object-has-acessible-name-8fc3b6.md
Labels: Editorial, Rule Update, reviewers wanted

#1380 page-has-title: improve example description
  _rules/html-page-title-2779a5.md
Labels: ACT TF request, reviewers wanted

#1401 Remove "clip" from Scrollable element definition
  pages/glossary/scrollable-element.md
Labels: Final Call 1 week

#1381 image-has-acc-name: applicability should not use the acc tree
  _rules/image-non-empty-accessible-name-23a2a8.md
Labels: ACT TF request, Final Call 1 week
