Repository act-rules/act-rules.github.io, pull requests merged in 2020-01, with the labels that each got.

#1086 Clean up glossary
  pages/glossary/generic-placeholder-text.md
  pages/glossary/non-streaming-media-element.md
  pages/glossary/rendered-text.md
  pages/glossary/standard-keyboard-navigation.md
  pages/glossary/visual-output.md
Labels: Definition, Editorial, reviewers wanted

#1081 Examples descriptions lang rules (5b7ae0 / bf051a / b5c3f8)
  _rules/html-page-lang-b5c3f8.md
  _rules/html-page-lang-valid-bf051a.md
  _rules/html-page-lang-xml-lang-match-5b7ae0.md
Labels: Editorial, reviewers wanted

#400 New rule: Heading has non-empty accessible name (ffd0e9)
  __tests__/spelling-ignore.yml
  _rules/heading-accessible-name-ffd0e9.md
Labels: Final call 2 weeks

#1090 Remove similar passed example for rule CSS Orientation Lock (b33eff)
  _rules/css-restrict-orientation-b33eff.md
Labels: Final Call 1 week

#1118 Put main defined term in italic
  __tests__/spelling-ignore.yml
  pages/glossary/accessible-name.md
  pages/glossary/equivalent-resource.md
  pages/glossary/explicit-role.md
  pages/glossary/filename.md
  pages/glossary/implicit-role.md
  pages/glossary/matching-characters.md
  pages/glossary/non-streaming-media-element.md
  pages/glossary/outcome.md
  pages/glossary/owned-by.md
  pages/glossary/rendered-text.md
  pages/glossary/same-resource.md
  pages/glossary/section-of-content.md
  pages/glossary/semantic-role.md
  pages/glossary/standard-keyboard-navigation.md
  pages/glossary/valid-language-subtag.md
  pages/glossary/visible.md
  pages/glossary/wai-aria-specifications.md
  pages/glossary/web-page-html.md
  pages/glossary/whitespace.md
Labels: Editorial, reviewers wanted

#1117 Add link to "image button state" for clarity (59796f)
  _rules/image-button-accessible-name-59796f.md
Labels: Editorial, reviewers wanted

#1114 Add note on difference between accessibility and DOM trees
  pages/glossary/owned-by.md
Labels: Agenda item

#1085 Metadata in glossary
  pages/glossary/accessible-name.md
  pages/glossary/appropriate-field-for-the-form-control.md
  pages/glossary/audio-output.md
  pages/glossary/correct-autocomplete-field.md
  pages/glossary/decorative.md
  pages/glossary/equivalent-resource.md
  pages/glossary/explicit-role.md
  pages/glossary/filename.md
  pages/glossary/focusable.md
  pages/glossary/implicit-role.md
  pages/glossary/included-in-the-accessibility-tree.md
  pages/glossary/matching-characters.md
  pages/glossary/non-streaming-media-element.md
  pages/glossary/outcome.md
  pages/glossary/owned-by.md
  pages/glossary/rendered-text.md
  pages/glossary/same-resource.md
  pages/glossary/section-of-content.md
  pages/glossary/semantic-role.md
  pages/glossary/standard-keyboard-navigation.md
  pages/glossary/valid-language-subtag.md
  pages/glossary/visible-text-content.md
  pages/glossary/visible.md
  pages/glossary/wai-aria-specifications.md
  pages/glossary/web-page-html.md
  pages/glossary/whitespace.md
Labels: Definition, Editorial, reviewers wanted

#1111 Replace all references to MDN
  _rules/html-page-lang-b5c3f8.md
  _rules/html-page-lang-valid-bf051a.md
  _rules/html-page-lang-xml-lang-match-5b7ae0.md
  _rules/role-attribute-valid-value-674b10.md
Labels: Editorial, Final Call 1 week

#1116 Fix failed example for "Heading has accessible name" (ffd0e9)
  _rules/heading-accessible-name-ffd0e9.md
Labels: Final Call 1 week, Rule Update

#1112 Definition of "marked as decorative"
  _rules/aria-hidden-no-focusable-content-6cfa84.md
  _rules/heading-accessible-name-ffd0e9.md
  _rules/image-accessible-name-23a2a8.md
  _rules/link-accessible-name-c487ae.md
  pages/glossary/decorative.md
  pages/glossary/marked-as-decorative.md
Labels: Editorial, Final Call 1 week

#833 New rule: Text nodes have minimal contrast
  __tests__/spelling-ignore.yml
  _rules/text-contrast-afw4f7.md
  pages/glossary/background-colors-of-text.md
  pages/glossary/bounding-box-around-text.md
  pages/glossary/disabled-element.md
  pages/glossary/foreground-colors-of-text.md
  pages/glossary/highest-possible-contrast.md
  pages/glossary/large-scale-text.md
  test-assets/contrast/black-hole.jpeg
  test-assets/contrast/example.png
Labels: Final call 2 weeks

#1121 Improve applicability of "button has accessible name" (97a4e1)
  _rules/button-accessible-name-97a4e1.md
Labels: Editorial, Final Call 1 week

#979 Rule: Table header cells have assigned data cells (d0f69e)
  __tests__/spelling-ignore.yml
  _rules/table-header-cells-refer-to-data-cells-d0f69e.md
Labels: Final call 2 weeks, Rule

#245 Rule: aria-required-owned-element
  _rules/aria-required-owned-element-bc4a75.md
Labels: Final call 2 weeks, Rule, WAI-Tools Year 1.5
