Repository act-rules/act-rules.github.io, pull requests merged in 2021-06, with the labels that each got.

#1628 Update video-alternative-for-auditory-eac66b.md
  _rules/video-alternative-for-auditory-eac66b.md
Labels: Rule

#1631 "role attribute has valid value" (674b10): Replace 'included in the accessibility tree' with 'hidden state is false'
  _rules/role-attribute-valid-value-674b10.md
Labels: Review Call 1 week, Rule Update

#1554 "ARIA required context role" (ff89c9): resolve TF feedback
  _rules/aria-required-context-role-ff89c9.md
Labels: Review Call 1 week, Rule Update

#1547 "Element with `lang` attribute has valid language tag" (de46e4): Apply to body and ignore attributes with no effect
  _rules/element-lang-valid-de46e4.md
Labels: Review Call 1 week, Rule Update

#1575 Editorial pass at example descriptions
  __tests__/spelling-ignore.yml
  _rules/attr-not-duplicated-e6952f.md
Labels: Editorial, Review Call 1 week

#1646 Update css-restrict-orientation-b33eff.md with better example
  _rules/css-restrict-orientation-b33eff.md
Labels: reviewers wanted

#1609 meta-viewport: remove delayed refresh from example
  _rules/meta-viewport-b4f0c3.md
Labels: Review Call 1 week

#1612 Update aria-state-or-property-permitted-5c01ea.md
  _rules/aria-state-or-property-permitted-5c01ea.md
Labels: Review Call 1 week, reviewers wanted

#1640 Update heading-non-empty-accessible-name-ffd0e9.md
  _rules/heading-non-empty-accessible-name-ffd0e9.md
Labels: Review call 2 weeks, Rule, reviewers wanted

#1632 Instrument accessibility note
  _rules/aria-state-or-property-permitted-5c01ea.md
  _rules/attr-not-duplicated-e6952f.md
  _rules/audio-or-video-avoids-automatically-playing-audio-80f0bf.md
  _rules/auto-update-text-efbfc7.md
  _rules/bypass-blocks-cf77f2.md
  _rules/device-motion-disabled-c249d5.md
  _rules/device-motion-user-interface-7677a9.md
  _rules/meta-viewport-b4f0c3.md
  _rules/printable-characters-shortcut-ffbc54.md
  pages/glossary/instrument.md
Labels: Editorial, reviewers wanted

#1648 No keyboard shortcut uses only printable characters [ffbc54]
  __tests__/spelling-ignore.yml
  _rules/printable-characters-shortcut-ffbc54.md
Labels: reviewers wanted
