Repository act-rules/act-rules.github.io, pull requests merged in 2021-09, with the labels that each got.

#1692 Replace "Final Call" by "Call for Review" in PR template and Process document
  .github/PULL_REQUEST_TEMPLATE.md
  pages/design/process.md
Labels: Editorial, reviewers wanted, Website content

#1671 Define that "semantic X" means "semantic role of X"
  _rules/aria-required-owned-element-bc4a75.md
  _rules/aria-state-or-property-permitted-5c01ea.md
  _rules/document-has-headings-for-non-repeated-content-047fe0.md
  _rules/form-field-non-empty-accessible-name-e086e5.md
  _rules/heading-descriptive-b49b2e.md
  _rules/heading-non-empty-accessible-name-ffd0e9.md
  _rules/image-non-empty-accessible-name-23a2a8.md
  _rules/link-alone-descriptive-aizyf1.md
  _rules/link-in-context-descriptive-5effbb.md
  _rules/link-non-empty-accessible-name-c487ae.md
  _rules/menuitem-non-empty-name-m6b1q3.md
  _rules/role-attribute-valid-value-674b10.md
  pages/glossary/semantic-role.md
Labels: Review Call 1 week

#1669 Replace semantic widget/link definitions
  _rules/document-has-landmark-with-non-repeated-content-b40fd1.md
  _rules/link-alone-descriptive-aizyf1.md
  _rules/link-in-context-descriptive-5effbb.md
  _rules/links-identical-name-equivalent-purpose-b20e66.md
  _rules/links-with-identical-names-and-context-serve-equivalent-purpose-fd3a94.md
  _rules/printable-characters-shortcut-ffbc54.md
  _rules/table-header-cell-has-assigned-cells-d0f69e.md
  _rules/text-contrast-afw4f7.md
  _rules/text-contrast-enhanced-09o5cg.md
  pages/glossary/inheriting-semantic-role.md
  pages/glossary/semantic-link.md
  pages/glossary/semantic-widget.md
Labels: Review Call 1 week

#1665 Don't allow description track to satisfy media SCs
  _rules/video-alternative-for-visual-c5a4ea.md
  _rules/video-as-media-alternative-ab4d13.md
  _rules/video-only-alternative-for-visual-c3232f.md
  _rules/video-strict-alternative-for-visual-1ec09b.md
Labels: Review Call 1 week

#1702 Making sure images are displayed- 46ca7f
  _rules/element-marked-decorative-is-not-exposed-46ca7f.md
Labels: reviewers wanted

#1675 Replace autocomplete value with a failing value
  _rules/autocomplete-valid-value-73f2c2.md
Labels: Definition, reviewers wanted, Review Call 1 week

#1699 Replace Hidden State by Programmatically Hidden
  _rules/image-non-empty-accessible-name-23a2a8.md
  _rules/role-attribute-valid-value-674b10.md
  pages/glossary/marked-as-decorative.md
  pages/glossary/programmatically-hidden.md
  pages/glossary/semantic-role.md
Labels: Editorial, reviewers wanted

#1707 Update autocomplete-valid-value-73f2c2.md
  _rules/autocomplete-valid-value-73f2c2.md
Labels: Editorial

#1690 "Text has enhanced contrast" [09o5cg]: make failed examples satisfy 1.4.3
  _rules/text-contrast-enhanced-09o5cg.md
Labels: Rule Update, Review Call 1 week

#1651 Heading is descriptive: Clarify expectations
  _rules/heading-descriptive-b49b2e.md
Labels: Rule Update, Review Call 1 week

#1650 Update assumption on lang codes to explicitly reject ISO 639.2
  __tests__/spelling-ignore.yml
  _rules/element-lang-matches-default-language-off6ek.md
  _rules/element-lang-valid-de46e4.md
  _rules/html-page-lang-b5c3f8.md
  _rules/html-page-lang-matches-default-ucwvc8.md
  _rules/html-page-lang-valid-bf051a.md
  _rules/html-page-lang-xml-lang-match-5b7ae0.md
  pages/glossary/valid-language-tag.md
Labels: Rule Update, Editorial, reviewers wanted

#1708 HTML page has lang: use "attribute value" definition
  _rules/html-page-lang-b5c3f8.md
Labels: reviewers wanted

#1705 Update autocomplete-valid-value-73f2c2.md
  _rules/autocomplete-valid-value-73f2c2.md
Labels: Editorial

#1713 Update elm-lang-valid example descriptions
  _rules/element-lang-valid-de46e4.md
Labels: reviewers wanted
