Repository act-rules/act-rules.github.io, pull requests merged in 2021-07, with the labels that each got.

#1569 aria-required-context: Replace the assumption
  _rules/aria-required-context-role-ff89c9.md
Labels: Review Call 1 week

#1647 Updates to 'video element visual content has transcript'
  _rules/video-transcript-1a02b0.md
Labels: Review call 2 weeks

#1636 define namespaced elements
  __tests__/spelling-ignore.yml
  _rules/aria-required-context-role-ff89c9.md
  _rules/aria-required-owned-element-bc4a75.md
  _rules/aria-state-or-property-permitted-5c01ea.md
  _rules/aria-state-or-property-valid-value-6a7281.md
  _rules/focusable-no-keyboard-trap-80af7b.md
  _rules/focusable-no-keyboard-trap-non-standard-nav-ebe86a.md
  _rules/focusable-no-keyboard-trap-standard-nav-a1b64e.md
  _rules/id-value-unique-3ea0c8.md
  _rules/links-identical-name-equivalent-purpose-b20e66.md
  _rules/links-with-identical-names-and-context-serve-equivalent-purpose-fd3a94.md
  _rules/presentational-children-no-focusable-content-307n5z.md
  _rules/role-attribute-valid-value-674b10.md
  _rules/role-required-states-and-properties-4e8ab6.md
  pages/glossary/namespaced-element.md
Labels: Review Call 1 week

#1610 link has name: Fix missing tabindex on passed example 2
  _rules/link-non-empty-accessible-name-c487ae.md
Labels: Review Call 1 week

#1659 Clarify 'one of the following' phrases
  _rules/aria-required-owned-element-bc4a75.md
  _rules/auto-update-text-efbfc7.md
  _rules/autocomplete-valid-value-73f2c2.md
  _rules/device-motion-disabled-c249d5.md
  _rules/device-motion-user-interface-7677a9.md
  _rules/focusable-no-keyboard-trap-80af7b.md
  _rules/image-accessible-name-descriptive-qt1vmo.md
  _rules/image-not-in-acc-tree-is-decorative-e88epe.md
  _rules/letter-spacing-not-important-24afc2.md
  _rules/line-height-not-important-78fd32.md
  _rules/scrollable-element-keyboard-accessible-0ssw9k.md
  _rules/text-contrast-afw4f7.md
  _rules/text-contrast-enhanced-09o5cg.md
  _rules/word-spacing-not-important-9e45ec.md
  _rules/zoom-text-no-overflow-clipping-59br37.md
  pages/design/rule-design.md
  pages/glossary/disabled-element.md
  pages/glossary/marked-as-decorative.md
  pages/glossary/programmatically-determined-link-context.md
  pages/glossary/text-inheriting-language.md
Labels: Review call 2 weeks

#1649 Update aria-state-or-property-valid-value-6a7281.md
  _rules/aria-state-or-property-valid-value-6a7281.md
Labels: reviewers wanted

#1657 Typos
  _rules/bypass-blocks-cf77f2.md
  _rules/document-has-headings-for-non-repeated-content-047fe0.md
  _rules/document-has-instrument-to-non-repeated-content-ye5d6e.md
Labels: Editorial, reviewers wanted

#1653 autocomplete: remove invalid example
  _rules/autocomplete-valid-value-73f2c2.md
Labels: Review Call 1 week

#1630 table-header-has-assigned-cells: Remove H43 from mapping
  _rules/table-header-cell-has-assigned-cells-d0f69e.md
Labels: Review call 2 weeks

#1561 Minor formatting changes to Expectations section
  _rules/video-alternative-for-visual-c5a4ea.md
Labels: Editorial, Rule Update, reviewers wanted
