Repository act-rules/act-rules.github.io, pull requests merged in 2022-09, with the labels that each got.

#1852 TF Work for survey results on object names
  _rules/object-has-acessible-name-8fc3b6.md
Labels: Review Call 1 week

#1899 Dependencies updates
  .github/workflows/dispatch.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
  .github/workflows/wai-deploy.yml
  _rules/__tests__/testcase-html-hint.js
  package-lock.json
  package.json
Labels: dependencies

#1906 Add "logo" to accessible name of images where relevant
  _rules/image-accessible-name-descriptive-qt1vmo.md
  _rules/image-not-in-acc-tree-is-decorative-e88epe.md
  _rules/object-has-acessible-name-8fc3b6.md
Labels: Rule Update, Review Call 1 week

#1920 Add secondary requirements to rules
  .gitignore
  _rules/image-no-text-0va7u6.md
  _rules/link-in-context-descriptive-5effbb.md
  _rules/link-non-empty-accessible-name-c487ae.md
  _rules/links-with-identical-names-and-context-serve-equivalent-purpose-fd3a94.md
  _rules/meta-refresh-no-delay-bc659a.md
  _rules/scrollable-element-keyboard-accessible-0ssw9k.md
  _rules/text-contrast-afw4f7.md
  _rules/video-alternative-for-visual-c5a4ea.md
  package-lock.json
Labels: Review Call 1 week
