Repository act-rules/act-rules.github.io, pull requests merged in 2022-11, with the labels that each got.

#1925 Remove one-item exception from the focus visible rule
  _rules/sequentially-focusable-element-has-visible-focus-oj04fd.md
Labels: Review Call 1 week

#1855 Actioning feedback from Survey on iFrames
  _rules/iframe-not-focusable-has-no-interactive-content-akn7bn.md
Labels: Rule Update, Review Call 1 week

#1955 Update image-accessible-name-descriptive-qt1vmo.md
  _rules/image-accessible-name-descriptive-qt1vmo.md
Labels: Review Call 1 week

#1958 meta refresh (no exceptions) examples should not fail SC 2.2.1
  _rules/meta-refresh-no-delay-no-exception-bisz58.md
Labels: Priority, Review Call 1 week

#1950 Update ACT Rules to use WAI-ARIA 1.2
  _rules/aria-attr-defined-5f99a7.md
  _rules/aria-required-context-role-ff89c9.md
  _rules/aria-required-owned-element-bc4a75.md
  _rules/aria-state-or-property-permitted-5c01ea.md
  _rules/aria-state-or-property-valid-value-6a7281.md
  _rules/form-field-label-descriptive-cc0f0a.md
  _rules/form-field-non-empty-accessible-name-e086e5.md
  _rules/invalid-form-field-value-36b590.md
  _rules/presentational-children-no-focusable-content-307n5z.md
  _rules/role-attribute-valid-value-674b10.md
  _rules/role-required-states-and-properties-4e8ab6.md
  pages/glossary/explicit-role.md
  pages/glossary/wai-aria-specifications.md
Labels: Review call 2 weeks, WAI-ARIA 1.2

#1917 Update scrollable-element-keyboard-accessible-0ssw9k.md
  __tests__/spelling-ignore.yml
  _rules/scrollable-element-keyboard-accessible-0ssw9k.md
Labels: Review Call 1 week

#1945 Adds consistency to accessibility support and assumptions wording
  _rules/aria-attr-defined-5f99a7.md
  _rules/aria-state-or-property-permitted-5c01ea.md
  _rules/attr-not-duplicated-e6952f.md
  _rules/audio-as-media-alternative-afb423.md
  _rules/audio-text-alternative-e7aa44.md
  _rules/audio-transcript-2eb176.md
  _rules/auto-play-audio-does-not-exceed-3-seconds-aaa1bf.md
  _rules/auto-play-audio-has-control-mechanism-4c31df.md
  _rules/auto-update-text-efbfc7.md
  _rules/block-collapsible-3e12e1.md
  _rules/css-restrict-orientation-b33eff.md
  _rules/device-motion-disabled-c249d5.md
  _rules/device-motion-user-interface-7677a9.md
  _rules/document-has-instrument-to-non-repeated-content-ye5d6e.md
  _rules/element-lang-matches-default-language-off6ek.md
  _rules/element-marked-decorative-is-not-exposed-46ca7f.md
  _rules/focusable-no-keyboard-trap-80af7b.md
  _rules/focusable-no-keyboard-trap-non-standard-nav-ebe86a.md
  _rules/focusable-no-keyboard-trap-standard-nav-a1b64e.md
  _rules/form-field-non-empty-accessible-name-e086e5.md
  _rules/heading-non-empty-accessible-name-ffd0e9.md
  _rules/html-page-lang-b5c3f8.md
  _rules/html-page-lang-matches-default-ucwvc8.md
  _rules/html-page-lang-valid-bf051a.md
  _rules/html-page-non-empty-title-2779a5.md
  _rules/id-value-unique-3ea0c8.md
  _rules/iframe-not-focusable-has-no-interactive-content-akn7bn.md
  _rules/image-accessible-name-descriptive-qt1vmo.md
  _rules/image-filename-as-accessible-name-9eb3f6.md
  _rules/image-no-text-0va7u6.md
  _rules/image-non-empty-accessible-name-23a2a8.md
  _rules/image-not-in-acc-tree-is-decorative-e88epe.md
  _rules/invalid-form-field-value-36b590.md
  _rules/links-with-identical-names-and-context-serve-equivalent-purpose-fd3a94.md
  _rules/non-visual-reference-alternative-9bd38c.md
  _rules/sequentially-focusable-element-has-visible-focus-oj04fd.md
  _rules/table-headers-attribute-refer-to-data-cells-a25f45.md
  _rules/video-alternative-for-auditory-eac66b.md
  _rules/video-as-media-alternative-ab4d13.md
  _rules/video-captions-f51b46.md
  _rules/video-only-as-media-alternative-fd26cf.md
  _rules/video-only-audio-track-d7ba54.md
  _rules/video-only-transcript-ee13b5.md
  _rules/video-transcript-1a02b0.md
  pages/design/atomic-template-empty.md
  pages/design/composite-template-empty.md
  pages/design/rule-template.md
Labels: Review Call 1 week

#1974 Form field name passed example should actually pass
  _rules/form-field-non-empty-accessible-name-e086e5.md
Labels: reviewers wanted, Priority

#1976 Object has accessible name: Fixing typo in file name
  _rules/object-has-accessible-name-8fc3b6.md
Labels: Editorial

#1961 Color contrast survey updates
  __tests__/spelling-ignore.yml
  _rules/text-contrast-afw4f7.md
  _rules/text-contrast-enhanced-09o5cg.md
  pages/glossary/highest-possible-contrast.md
Labels: Rule, Definition, Review Call 1 week

#1977 Updates to remark-parse@9.0.0 - eliminates vulnerabilities
  package-lock.json
  package.json
Labels: reviewers wanted, security
