Repository act-rules/act-rules.github.io, pull requests merged in 2022-05, with the labels that each got.

#1837 Update implementation info
  __tests__/spelling-ignore.yml
  pages/implementations/earl-reports.md
  pages/implementations/testcases.md
Labels: reviewers wanted

#1828 Update audio-text-alternative-e7aa44.md from TF survey responses
  _rules/audio-text-alternative-e7aa44.md
Labels: Rule Update, Review Call 1 week

#1825 form field error: Improve on examples
  _rules/invalid-form-field-value-36b590.md
Labels: Review Call 1 week

#1826 form label descriptive: Tweak the examples
  _rules/form-field-label-descriptive-cc0f0a.md
Labels: Review Call 1 week

#1829 Element lang correct: remove inapplicable examples
  _rules/element-lang-matches-default-language-off6ek.md
Labels: Review Call 1 week

#1765 Include ancestor generating a block container in the programatically determined link context definition
  _rules/links-with-identical-names-and-context-serve-equivalent-purpose-fd3a94.md
  pages/glossary/programmatically-determined-link-context.md
Labels: Definition, Review call 2 weeks

#1794 Update "focusable element has no keyboard trap" examples to not use single key shortcuts (80af7b)
  _rules/focusable-no-keyboard-trap-80af7b.md
  _rules/focusable-no-keyboard-trap-non-standard-nav-ebe86a.md
  _rules/focusable-no-keyboard-trap-standard-nav-a1b64e.md
  test-assets/focusable-no-keyboard-trap/keyboard.js
Labels: Rule Update, Review call 2 weeks

#1844 akn7bn -- Makes sentence easier to process
  _rules/iframe-not-focusable-has-no-interactive-content-akn7bn.md
Labels: Editorial

#1818 Add more examples of invisible elements
  pages/examples/visible.md
Labels: Editorial, Review Call 1 week

#1841 Update format for rule names
  __tests__/spelling-ignore.yml
  _rules/aria-attr-defined-5f99a7.md
  _rules/aria-hidden-no-focusable-content-6cfa84.md
  _rules/audio-as-media-alternative-afb423.md
  _rules/audio-or-video-avoids-automatically-playing-audio-80f0bf.md
  _rules/audio-text-alternative-e7aa44.md
  _rules/audio-transcript-2eb176.md
  _rules/auto-play-audio-does-not-exceed-3-seconds-aaa1bf.md
  _rules/auto-play-audio-has-control-mechanism-4c31df.md
  _rules/autocomplete-valid-value-73f2c2.md
  _rules/element-lang-valid-de46e4.md
  _rules/explicit-SVG-image-non-empty-accessible-name-7d6734.md
  _rules/html-page-lang-b5c3f8.md
  _rules/html-page-lang-valid-bf051a.md
  _rules/html-page-lang-xml-lang-match-5b7ae0.md
  _rules/id-value-unique-3ea0c8.md
  _rules/iframe-identical-name-equivalent-purpose-4b1c6c.md
  _rules/iframe-non-empty-accessible-name-cae760.md
  _rules/iframe-not-focusable-has-no-interactive-content-akn7bn.md
  _rules/letter-spacing-not-important-24afc2.md
  _rules/line-height-not-important-78fd32.md
  _rules/meta-refresh-no-delay-bc659a.md
  _rules/meta-refresh-no-delay-no-exception-bisz58.md
  _rules/meta-viewport-b4f0c3.md
  _rules/role-attribute-valid-value-674b10.md
  _rules/role-required-states-and-properties-4e8ab6.md
  _rules/table-headers-attribute-refer-to-data-cells-a25f45.md
  _rules/video-alternative-for-auditory-eac66b.md
  _rules/video-alternative-for-visual-c5a4ea.md
  _rules/video-as-media-alternative-ab4d13.md
  _rules/video-audio-description-1ea59c.md
  _rules/video-captions-f51b46.md
  _rules/video-description-track-f196ce.md
  _rules/video-only-alternative-for-visual-c3232f.md
  _rules/video-only-as-media-alternative-fd26cf.md
  _rules/video-only-audio-track-d7ba54.md
  _rules/video-only-description-track-ac7dc6.md
  _rules/video-only-transcript-ee13b5.md
  _rules/video-strict-alternative-for-visual-1ec09b.md
  _rules/video-transcript-1a02b0.md
  _rules/word-spacing-not-important-9e45ec.md
  pages/design/rule-design.md
Labels: Review Call 1 week

#1809 form-field descriptive label: Improve the examples
  _rules/form-field-label-descriptive-cc0f0a.md
Labels: Review Call 1 week

#1821 Add note to button has accessible name rule to explain the exception #97a4e1
  _rules/button-non-empty-accessible-name-97a4e1.md
Labels: Rule Update, Review Call 1 week
