Repository act-rules/act-rules.github.io, pull requests merged in 2022-10, with the labels that each got.

#1877 Adds prohibited attributes expectation to rule 5c01ea
  _rules/aria-state-or-property-permitted-5c01ea.md
Labels: reviewers wanted, WAI-ARIA 1.2

#1936 update 5f99a7 to aria 1.2
  _rules/aria-attr-defined-5f99a7.md
Labels: WAI-ARIA 1.2

#1937 update ff89c9 to aria 1.2
  _rules/aria-required-context-role-ff89c9.md
Labels: WAI-ARIA 1.2

#1944 update 36b590 to aria 1.2
  _rules/invalid-form-field-value-36b590.md
Labels: WAI-ARIA 1.2

#1946 update cc0f0a to aria 1.2
  _rules/form-field-label-descriptive-cc0f0a.md
Labels: WAI-ARIA 1.2

#1948 update 674b10 to aria 1.2
  _rules/role-attribute-valid-value-674b10.md
Labels: WAI-ARIA 1.2

#1940 update bc4a75 to aria 1.2
  _rules/aria-required-owned-element-bc4a75.md
Labels: WAI-ARIA 1.2

#1947 update 307n5z to aria 1.2
  _rules/presentational-children-no-focusable-content-307n5z.md
Labels: WAI-ARIA 1.2

#1942 Form field accessible name: explicit that role inheriting from `menuitem` are to be considered
  _rules/form-field-non-empty-accessible-name-e086e5.md
Labels: reviewers wanted, WAI-ARIA 1.2

#1932 meta-refresh fix issue with flickering note
  _rules/meta-refresh-no-delay-bc659a.md
  _rules/meta-refresh-no-delay-no-exception-bisz58.md
Labels: AGWG request

#1912 c4a8a4 -- Updates to web page definition and editorials
  _rules/html-page-title-descriptive-c4a8a4.md
Labels: Review Call 1 week

#1941 Removes outdated accessibility support notes
  _rules/form-field-non-empty-accessible-name-e086e5.md
  _rules/iframe-non-empty-accessible-name-cae760.md
  _rules/image-button-non-empty-accessible-name-59796f.md
  _rules/image-non-empty-accessible-name-23a2a8.md
  _rules/link-non-empty-accessible-name-c487ae.md
Labels: Review Call 1 week

#1931 Update object rule decorative assumption
  _rules/object-has-acessible-name-8fc3b6.md
Labels: Review Call 1 week, AGWG request
