Repository act-rules/act-rules.github.io, pull requests merged in 2022-06, with the labels that each got.

#1838 Create definition of play button and update "Audio element has text alternative" plus input rules (e7aa44, 2eb176, afb423)
  _rules/audio-as-media-alternative-afb423.md
  _rules/audio-text-alternative-e7aa44.md
  _rules/audio-transcript-2eb176.md
  pages/glossary/play-button.md
Labels: Rule Update, Definition, Review call 2 weeks

#1857 Editorial changed to programmatically hidden
  pages/glossary/programmatically-hidden.md
Labels: reviewers wanted

#1850 ARIA required owned elm; fix parser issue in pass 3
  _rules/aria-required-owned-element-bc4a75.md
Labels: Review Call 1 week

#1833 Unify expectations writing #1778
  _rules/audio-as-media-alternative-afb423.md
  _rules/video-as-media-alternative-ab4d13.md
  _rules/video-only-as-media-alternative-fd26cf.md
Labels: Review Call 1 week

#1819 6cfa84: Modify pass example 4 to be more realistic, using a dialog
  _rules/aria-hidden-no-focusable-content-6cfa84.md
Labels: Review Call 1 week

#1856 Add cross-table headers attribute example
  _rules/table-headers-attribute-refer-to-data-cells-a25f45.md
Labels: Review Call 1 week

#1835 b4f0c3: Adjust meta viewport applicability based on properties defined
  _rules/meta-viewport-b4f0c3.md
Labels: Rule Update, Review Call 1 week
