Repository act-rules/act-rules.github.io, pull requests merged in 2022-02, with the labels that each got.

#1773 Updated mechanisms to instruments in "Text content that changes automatically can be paused, stopped or hidden" (efbfc7)
  _rules/auto-update-text-efbfc7.md
Labels: Rule Update, Editorial, reviewers wanted

#1744 Use `dfn` elements for defining terms
  __tests__/link-to-glossary-term-valid.js
  _rules/aria-required-owned-element-bc4a75.md
  _rules/element-lang-matches-default-language-off6ek.md
  _rules/image-button-non-empty-accessible-name-59796f.md
  pages/glossary/attribute-value.md
  pages/glossary/text-inheriting-language.md
  test-utils/describe-page.js
  test-utils/describe-rule.js
  utils/get-ids.js
Labels: Editorial, Review Call 1 week

#1746 "Element language" rules: handle whitespace
  _rules/element-lang-matches-default-language-off6ek.md
  _rules/element-lang-valid-de46e4.md
Labels: reviewers wanted, Review Call 1 week

#1786 Update video description rules
  _rules/video-description-track-f196ce.md
  _rules/video-only-description-track-ac7dc6.md
Labels: Review call 2 weeks

#1798 image-filename: Use US grammer "superseded"
  _rules/image-filename-as-accessible-name-9eb3f6.md
Labels: reviewers wanted

#1764 Update programmatically-hidden.md
  pages/glossary/programmatically-hidden.md
Labels: Definition, Review call 2 weeks, reviewers wanted

#1775 Updated examples to ensure tests are case insensitive in valid lang tag rules
  _rules/element-lang-matches-default-language-off6ek.md
  _rules/element-lang-valid-de46e4.md
  _rules/html-page-lang-matches-default-ucwvc8.md
  _rules/html-page-lang-valid-bf051a.md
  _rules/html-page-lang-xml-lang-match-5b7ae0.md
Labels: Rule Update, reviewers wanted, Review Call 1 week
