Repository act-rules/act-rules.github.io, pull requests merged in 2022-04, with the labels that each got.

#1808 Editorials to 'audio has alternative' rules
  _rules/audio-as-media-alternative-afb423.md
  _rules/audio-text-alternative-e7aa44.md
  _rules/audio-transcript-2eb176.md
Labels: Review Call 1 week

#1779 Survey amendments iframe-not-focusable-has-no-interactive-content-akn7bn
  _rules/iframe-not-focusable-has-no-interactive-content-akn7bn.md
Labels: Review call 2 weeks

#1822 Editorial updates to the meta-viewport rule
  _rules/meta-viewport-b4f0c3.md
Labels: reviewers wanted, Review Call 1 week
