Repository act-rules/act-rules.github.io, pull requests merged in 2022-01, with the labels that each got.

#1774 Update CG website pages
  __deprecated__/pages/contribute/join.md
  __deprecated__/pages/contribute/propose-rules.md
  __deprecated__/pages/contribute/rule-feedback.md
  pages/about.md
  pages/communication.md
  pages/contribute.md
  pages/joining.md
Labels: Website content

#1771 a25f45 Moves notes to background
  _rules/table-headers-attribute-refer-to-data-cells-a25f45.md
Labels: reviewers wanted, ACT TF request

#1772 a25f45 Adds assumption that id values are unique
  _rules/table-headers-attribute-refer-to-data-cells-a25f45.md
Labels: reviewers wanted, ACT TF request

#1756 Remove 2nd WCAG reference: 1.4.10
  _rules/meta-viewport-b4f0c3.md
Labels: Review Call 1 week

#1762 elm marked as decorative: Update the examples
  _rules/element-marked-decorative-is-not-exposed-46ca7f.md
Labels: Review Call 1 week

#1760 Adding DPUB use cases
  _rules/link-non-empty-accessible-name-c487ae.md
Labels: Review Call 1 week
