Repository act-rules/act-rules.github.io, pull requests merged in 2023-10, with the labels that each got.

#1994 "Meta viewport allows for zoom" (b4f0c3): Explicit meaning of 'has'
  _rules/meta-viewport-b4f0c3.md
Labels: Rule Update, Review Call 1 week

#2120 Map Empty-heading rule to ARIA instead of WCAG
  _rules/heading-non-empty-accessible-name-ffd0e9.md
Labels: Review call 2 weeks

#2117 Deprecate 4.1.1 parsing rules
  _rules/attr-not-duplicated-e6952f.md
  _rules/id-value-unique-3ea0c8.md
Labels: Review call 2 weeks

#2125 "Iframe not with interactive element" [akn7bn]: handle inert iframe
  __tests__/spelling-ignore.yml
  _rules/iframe-with-interactive-content-in-tab-order-akn7bn.md
  pages/glossary/inert.md
Labels: reviewers wanted

#2089 "Video element auditory content has captions" [f51b46]: Adding 1.2.1 as a secondary requirement.
  _rules/video-captions-f51b46.md
Labels: Review Call 1 week
