Repository act-rules/act-rules.github.io, pull requests merged in 2023-08, with the labels that each got.

#2086 Deprecate HTML page lang and xml:lang attributes have matching values
  _rules/html-page-lang-xml-lang-match-5b7ae0.md
Labels: Review call 2 weeks

#2079 "Iframe element has non-empty accessible name" [cae760]: rephrase Applicability
  _rules/iframe-non-empty-accessible-name-cae760.md
Labels: Editorial, reviewers wanted

#2078 "Iframe with interactive elements is not excluded from tab-order" [akn7bn]: rename file
  _rules/iframe-with-interactive-content-in-tab-order-akn7bn.md
Labels: Editorial, reviewers wanted

#2060 Move secondary requirement texts out of the background
  __tests__/frontmatter.js
  __tests__/link-to-glossary-term-valid.js
  __tests__/spelling-ignore.yml
  _rules/aria-attr-defined-5f99a7.md
  _rules/aria-state-or-property-permitted-5c01ea.md
  _rules/aria-state-or-property-valid-value-6a7281.md
  _rules/image-no-text-0va7u6.md
  _rules/link-in-context-descriptive-5effbb.md
  _rules/link-non-empty-accessible-name-c487ae.md
  _rules/links-identical-name-equivalent-purpose-b20e66.md
  _rules/links-with-identical-names-and-context-serve-equivalent-purpose-fd3a94.md
  _rules/meta-refresh-no-delay-bc659a.md
  _rules/meta-refresh-no-delay-no-exception-bisz58.md
  _rules/meta-viewport-b4f0c3.md
  _rules/role-attribute-valid-value-674b10.md
  _rules/role-required-states-and-properties-4e8ab6.md
  _rules/scrollable-element-keyboard-accessible-0ssw9k.md
  _rules/text-contrast-afw4f7.md
  _rules/text-contrast-enhanced-09o5cg.md
  _rules/video-alternative-for-visual-c5a4ea.md
  pages/design/atomic-template-empty.md
  pages/design/composite-template-empty.md
  pages/design/manual-template-empty.md
  pages/design/rule-design.md
  pages/design/rule-template.md
Labels: Review Call 1 week

#2100 Update element-lang-valid-de46e4.md
  _rules/element-lang-valid-de46e4.md
Labels: Review Call 1 week
