Repository act-rules/act-rules.github.io, pull requests merged in 2023-01, with the labels that each got.

#1969 Clarify image of text rule
  _rules/image-no-text-0va7u6.md
  pages/glossary/essential-text-presentation.md
  pages/glossary/insignificant.md
Labels: Review Call 1 week

#1998 Update templates to ARIA 1.2 and fix typos
  __tests__/spelling.js
  pages/design/atomic-template-empty.md
  pages/design/composite-template-empty.md
  pages/design/rule-template.md
  test-utils/describe-page.js
  test-utils/describe-rule.js
Labels: Editorial, reviewers wanted

#1987 Link rules to WAI site rather than CG site
  _rules/aria-hidden-no-focusable-content-6cfa84.md
  _rules/aria-state-or-property-permitted-5c01ea.md
  _rules/aria-state-or-property-valid-value-6a7281.md
  _rules/audio-or-video-avoids-automatically-playing-audio-80f0bf.md
  _rules/audio-text-alternative-e7aa44.md
  _rules/button-non-empty-accessible-name-97a4e1.md
  _rules/bypass-blocks-cf77f2.md
  _rules/element-lang-matches-default-language-off6ek.md
  _rules/focusable-no-keyboard-trap-80af7b.md
  _rules/html-page-lang-b5c3f8.md
  _rules/html-page-lang-matches-default-ucwvc8.md
  _rules/html-page-lang-valid-bf051a.md
  _rules/html-page-non-empty-title-2779a5.md
  _rules/html-page-title-descriptive-c4a8a4.md
  _rules/image-button-non-empty-accessible-name-59796f.md
  _rules/image-filename-as-accessible-name-9eb3f6.md
  _rules/link-alone-descriptive-aizyf1.md
  _rules/link-in-context-descriptive-5effbb.md
  _rules/link-non-empty-accessible-name-c487ae.md
  _rules/presentational-children-no-focusable-content-307n5z.md
  _rules/scrollable-element-keyboard-accessible-0ssw9k.md
  _rules/video-alternative-for-auditory-eac66b.md
  _rules/video-alternative-for-visual-c5a4ea.md
  _rules/video-only-alternative-for-visual-c3232f.md
  _rules/video-strict-alternative-for-visual-1ec09b.md
Labels: reviewers wanted

#1986 Add more secondary requirements
  __tests__/frontmatter.js
  _rules/aria-attr-defined-5f99a7.md
  _rules/aria-state-or-property-permitted-5c01ea.md
  _rules/aria-state-or-property-valid-value-6a7281.md
  _rules/link-non-empty-accessible-name-c487ae.md
  _rules/meta-refresh-no-delay-no-exception-bisz58.md
  _rules/role-attribute-valid-value-674b10.md
  _rules/role-required-states-and-properties-4e8ab6.md
  _rules/text-contrast-enhanced-09o5cg.md
  package-lock.json
Labels: Priority, Review Call 1 week

#1992 Add assumption about email titles
  _rules/html-page-non-empty-title-2779a5.md
Labels: Rule Update, Review Call 1 week

#1905 "Focusable element has no keyboard trap via standard navigation" [a1b64e]: fix Failed example and add clarification
  _rules/focusable-no-keyboard-trap-standard-nav-a1b64e.md
Labels: Rule Update, Review Call 1 week

#2004 ARIA props permitted; editorial updates
  _rules/aria-state-or-property-permitted-5c01ea.md
Labels: reviewers wanted

#2010 Add low-level fails to AAA rules
  _rules/meta-refresh-no-delay-no-exception-bisz58.md
  _rules/text-contrast-enhanced-09o5cg.md
Labels: Priority, Review Call 1 week
