Repository act-rules/act-rules.github.io, pull requests merged in 2024-08, with the labels that each got.

#2188 Update Form field has non-empty accessible name [e086e5]: Added secondary requirements for 1.3.1 and 2.5.3
  _rules/form-field-non-empty-accessible-name-e086e5.md
Labels: Review call 2 weeks

#2203 HTML page has non-empty title [2779a5]: Added HTML specs reference
  _rules/html-page-non-empty-title-2779a5.md
Labels: Editorial, reviewers wanted

#2178 Links with identical accessible names and same context serve equivalent purpose" [fd3a94]: Reduced images size for failed examples [4,8]
  _rules/links-with-identical-names-and-context-serve-equivalent-purpose-fd3a94.md
Labels: Editorial, reviewers wanted

#2202 New rule: Summary element has non-empty accessible name
  _rules/summary-non-empty-accessible-name-2t702h.md
Labels: Review call 2 weeks

#2184 Added text-shadow failure - Text has minimum contrast [afw4f7]
  __tests__/spelling-ignore.yml
  _rules/text-contrast-afw4f7.md
Labels: Review call 2 weeks

#2181 HTML page has non-empty title - #2779a5: updated Passed Example 2 description
  _rules/html-page-non-empty-title-2779a5.md
Labels: Review Call 1 week
