Repository act-rules/act-rules.github.io, pull requests merged in 2025-04, with the labels that each got.

#2304 summary name, fix markdown error
  _rules/summary-non-empty-accessible-name-2t702h.md
Labels: reviewers wanted

#2305 Updated required owned elms rule description
  _rules/aria-required-owned-element-bc4a75.md
Labels: reviewers wanted

#2240 [Editorial] - [5f99a7] ARIA attribute is defined in WAI-ARIA - Passed Example 2 improvement
  _rules/aria-attr-defined-5f99a7.md
Labels: Editorial, Review Call 1 week

#2274 [Accessibility support] - Empty alt attribute is now consistently supported
  _rules/image-non-empty-accessible-name-23a2a8.md
Labels: Review call 2 weeks, accessibility support

#2312 [a25f45] Headers attribute specified on a cell refers to cells in the same table element - Updated Inapplicable Example 6
  _rules/table-headers-attribute-refer-to-data-cells-a25f45.md
Labels: Review Call 1 week

#2313 [4e8ab6] Element with role attribute has required states and properties - Removed Combobox Failed Example 6
  _rules/role-required-states-and-properties-4e8ab6.md
Labels: Review call 2 weeks
