Repository act-rules/act-rules.github.io, pull requests merged in 2025-05, with the labels that each got.

#2267 [Editorial] - [d0f69e] Table header cell has assigned cells - Passed Example 2-4 improvement (acc name)
  _rules/table-header-cell-has-assigned-cells-d0f69e.md
Labels: Editorial, reviewers wanted

#2265 [Editorial] - [4e8ab6] Element with role attribute has required states and properties - Inapplicable Example 2 improvement (acc name)
  _rules/role-required-states-and-properties-4e8ab6.md
Labels: Editorial, reviewers wanted

#2263 [Editorial] - [4e8ab6] Element with role attribute has required states and properties - Passed Example 6 improvement (acc name)
  _rules/role-required-states-and-properties-4e8ab6.md
Labels: Editorial, reviewers wanted

#2255 [Editorial] - [5c01ea] ARIA state or property is permitted - Passed Example 6-7-8 improvement
  _rules/aria-state-or-property-permitted-5c01ea.md
Labels: Editorial, reviewers wanted

#2253 [Editorial] - [674b10] Role attribute has valid value - Inapplicable Example 4 improvement
  _rules/role-attribute-valid-value-674b10.md
Labels: Editorial, reviewers wanted

#2249 [Editorial] - [bc4a75] ARIA required owned elements - Passed Example 2 improvement
  _rules/aria-required-owned-element-bc4a75.md
Labels: Editorial, reviewers wanted

#2246 [Editorial] - [in6db8] ARIA required ID references exist - Passed Example 2 improvement
  _rules/aria-required-id-references-in6db8.md
Labels: Editorial, reviewers wanted

#2244 [Editorial] - [a25f45] Headers attribute specified on a cell refers to cells in the same table element - Inapplicable Example 4 improvement
  _rules/table-headers-attribute-refer-to-data-cells-a25f45.md
Labels: Editorial, reviewers wanted

#2229 Add 2.1.3 to iframe focusable rule
  _rules/iframe-with-interactive-content-in-tab-order-akn7bn.md
Labels: reviewers wanted

#2200 Text is clipped: "link to a full version"
  _rules/zoom-text-no-overflow-clipping-59br37.md
Labels: Editorial, Review Call 1 week

#2284 Unnecessary autocomplete support item
  _rules/autocomplete-valid-value-73f2c2.md
Labels: reviewers wanted

#2285 block-collapsible assumption under wrong heading
  _rules/block-collapsible-3e12e1.md
Labels: reviewers wanted

#2286 button name move assumption to the correct section
  _rules/button-non-empty-accessible-name-97a4e1.md
Labels: reviewers wanted

#2328 [4e8ab6] Fix aria mapping on the "Element with role attribute has required states and properties" rule
  _rules/role-required-states-and-properties-4e8ab6.md
Labels: Editorial
